// ╔══════════════════════════════════════════════════════╗
// ║  QuizNight – FLAG QUIZ Modus                         ║
// ║  195 Länder  ·  IDs 4001–4195                        ║
// ╚══════════════════════════════════════════════════════╝

export interface FlagQuestion {
  id: number; type: "flag";
  flag: string; code: string;
  answer: string; aliases?: string[];
  category: string; difficulty: "easy"|"medium"|"hard";
}

export const FLAG_QUESTIONS: FlagQuestion[] = [
  // ══ EUROPA – LEICHT/MITTEL ══
  { id:4001, type:"flag", flag:"🇩🇪", code:"de", answer:"Deutschland",      aliases:["germany"],                category:"Flaggenrätsel", difficulty:"easy" },
  { id:4002, type:"flag", flag:"🇫🇷", code:"fr", answer:"Frankreich",       aliases:["france"],                 category:"Flaggenrätsel", difficulty:"easy" },
  { id:4003, type:"flag", flag:"🇬🇧", code:"gb", answer:"Großbritannien",   aliases:["uk","england","britain","vereinigtes königreich"], category:"Flaggenrätsel", difficulty:"easy" },
  { id:4004, type:"flag", flag:"🇮🇹", code:"it", answer:"Italien",          aliases:["italy","italia"],         category:"Flaggenrätsel", difficulty:"easy" },
  { id:4005, type:"flag", flag:"🇪🇸", code:"es", answer:"Spanien",          aliases:["spain","españa"],         category:"Flaggenrätsel", difficulty:"easy" },
  { id:4006, type:"flag", flag:"🇨🇭", code:"ch", answer:"Schweiz",          aliases:["switzerland","suisse"],   category:"Flaggenrätsel", difficulty:"easy" },
  { id:4007, type:"flag", flag:"🇦🇹", code:"at", answer:"Österreich",       aliases:["austria"],                category:"Flaggenrätsel", difficulty:"easy" },
  { id:4008, type:"flag", flag:"🇳🇱", code:"nl", answer:"Niederlande",      aliases:["netherlands","holland"],  category:"Flaggenrätsel", difficulty:"easy" },
  { id:4009, type:"flag", flag:"🇧🇪", code:"be", answer:"Belgien",          aliases:["belgium"],                category:"Flaggenrätsel", difficulty:"easy" },
  { id:4010, type:"flag", flag:"🇸🇪", code:"se", answer:"Schweden",         aliases:["sweden"],                 category:"Flaggenrätsel", difficulty:"easy" },
  { id:4011, type:"flag", flag:"🇳🇴", code:"no", answer:"Norwegen",         aliases:["norway"],                 category:"Flaggenrätsel", difficulty:"easy" },
  { id:4012, type:"flag", flag:"🇩🇰", code:"dk", answer:"Dänemark",         aliases:["denmark"],                category:"Flaggenrätsel", difficulty:"easy" },
  { id:4013, type:"flag", flag:"🇵🇹", code:"pt", answer:"Portugal",         aliases:[],                         category:"Flaggenrätsel", difficulty:"easy" },
  { id:4014, type:"flag", flag:"🇬🇷", code:"gr", answer:"Griechenland",     aliases:["greece"],                 category:"Flaggenrätsel", difficulty:"easy" },
  { id:4015, type:"flag", flag:"🇮🇪", code:"ie", answer:"Irland",           aliases:["ireland"],                category:"Flaggenrätsel", difficulty:"easy" },
  { id:4016, type:"flag", flag:"🇵🇱", code:"pl", answer:"Polen",            aliases:["poland"],                 category:"Flaggenrätsel", difficulty:"easy" },
  { id:4017, type:"flag", flag:"🇫🇮", code:"fi", answer:"Finnland",         aliases:["finland"],                category:"Flaggenrätsel", difficulty:"easy" },
  { id:4018, type:"flag", flag:"🇹🇷", code:"tr", answer:"Türkei",           aliases:["turkey","türkiye"],       category:"Flaggenrätsel", difficulty:"easy" },
  { id:4019, type:"flag", flag:"🇺🇦", code:"ua", answer:"Ukraine",          aliases:[],                         category:"Flaggenrätsel", difficulty:"medium" },
  { id:4020, type:"flag", flag:"🇨🇿", code:"cz", answer:"Tschechien",       aliases:["czech republic"],         category:"Flaggenrätsel", difficulty:"medium" },
  { id:4021, type:"flag", flag:"🇭🇺", code:"hu", answer:"Ungarn",           aliases:["hungary"],                category:"Flaggenrätsel", difficulty:"medium" },
  { id:4022, type:"flag", flag:"🇷🇴", code:"ro", answer:"Rumänien",         aliases:["romania"],                category:"Flaggenrätsel", difficulty:"medium" },
  { id:4023, type:"flag", flag:"🇭🇷", code:"hr", answer:"Kroatien",         aliases:["croatia"],                category:"Flaggenrätsel", difficulty:"medium" },
  { id:4024, type:"flag", flag:"🇸🇰", code:"sk", answer:"Slowakei",         aliases:["slovakia"],               category:"Flaggenrätsel", difficulty:"medium" },
  { id:4025, type:"flag", flag:"🇸🇮", code:"si", answer:"Slowenien",        aliases:["slovenia"],               category:"Flaggenrätsel", difficulty:"medium" },
  { id:4026, type:"flag", flag:"🇧🇬", code:"bg", answer:"Bulgarien",        aliases:["bulgaria"],               category:"Flaggenrätsel", difficulty:"medium" },
  { id:4027, type:"flag", flag:"🇷🇸", code:"rs", answer:"Serbien",          aliases:["serbia"],                 category:"Flaggenrätsel", difficulty:"medium" },
  { id:4028, type:"flag", flag:"🇮🇸", code:"is", answer:"Island",           aliases:["iceland"],                category:"Flaggenrätsel", difficulty:"medium" },
  { id:4029, type:"flag", flag:"🇱🇺", code:"lu", answer:"Luxemburg",        aliases:["luxembourg"],             category:"Flaggenrätsel", difficulty:"medium" },
  { id:4030, type:"flag", flag:"🇧🇦", code:"ba", answer:"Bosnien-Herzegowina",aliases:["bosnien","bosnia"],     category:"Flaggenrätsel", difficulty:"medium" },
  { id:4031, type:"flag", flag:"🇦🇱", code:"al", answer:"Albanien",         aliases:["albania"],                category:"Flaggenrätsel", difficulty:"medium" },
  { id:4032, type:"flag", flag:"🇲🇰", code:"mk", answer:"Nordmazedonien",   aliases:["mazedonien","north macedonia"], category:"Flaggenrätsel", difficulty:"hard" },
  { id:4033, type:"flag", flag:"🇲🇪", code:"me", answer:"Montenegro",       aliases:[],                         category:"Flaggenrätsel", difficulty:"hard" },
  { id:4034, type:"flag", flag:"🇽🇰", code:"xk", answer:"Kosovo",           aliases:[],                         category:"Flaggenrätsel", difficulty:"hard" },
  { id:4035, type:"flag", flag:"🇲🇩", code:"md", answer:"Moldau",           aliases:["moldova"],                category:"Flaggenrätsel", difficulty:"hard" },
  { id:4036, type:"flag", flag:"🇧🇾", code:"by", answer:"Belarus",          aliases:["weißrussland","weissrussland"], category:"Flaggenrätsel", difficulty:"hard" },
  { id:4037, type:"flag", flag:"🇱🇹", code:"lt", answer:"Litauen",          aliases:["lithuania"],              category:"Flaggenrätsel", difficulty:"medium" },
  { id:4038, type:"flag", flag:"🇱🇻", code:"lv", answer:"Lettland",         aliases:["latvia"],                 category:"Flaggenrätsel", difficulty:"medium" },
  { id:4039, type:"flag", flag:"🇪🇪", code:"ee", answer:"Estland",          aliases:["estonia"],                category:"Flaggenrätsel", difficulty:"medium" },
  { id:4040, type:"flag", flag:"🇲🇹", code:"mt", answer:"Malta",            aliases:[],                         category:"Flaggenrätsel", difficulty:"hard" },
  { id:4041, type:"flag", flag:"🇨🇾", code:"cy", answer:"Zypern",           aliases:["cyprus"],                 category:"Flaggenrätsel", difficulty:"hard" },
  { id:4042, type:"flag", flag:"🇷🇺", code:"ru", answer:"Russland",         aliases:["russia"],                 category:"Flaggenrätsel", difficulty:"easy" },
  { id:4043, type:"flag", flag:"🇦🇩", code:"ad", answer:"Andorra",          aliases:[],                         category:"Flaggenrätsel", difficulty:"hard" },
  { id:4044, type:"flag", flag:"🇲🇨", code:"mc", answer:"Monaco",           aliases:[],                         category:"Flaggenrätsel", difficulty:"hard" },
  { id:4045, type:"flag", flag:"🇸🇲", code:"sm", answer:"San Marino",       aliases:[],                         category:"Flaggenrätsel", difficulty:"hard" },
  { id:4046, type:"flag", flag:"🇻🇦", code:"va", answer:"Vatikanstadt",     aliases:["vatikan","vatican"],      category:"Flaggenrätsel", difficulty:"hard" },
  { id:4047, type:"flag", flag:"🇱🇮", code:"li", answer:"Liechtenstein",    aliases:[],                         category:"Flaggenrätsel", difficulty:"hard" },

  // ══ ASIEN ══
  { id:4048, type:"flag", flag:"🇯🇵", code:"jp", answer:"Japan",            aliases:[],                         category:"Flaggenrätsel", difficulty:"easy" },
  { id:4049, type:"flag", flag:"🇨🇳", code:"cn", answer:"China",            aliases:[],                         category:"Flaggenrätsel", difficulty:"easy" },
  { id:4050, type:"flag", flag:"🇰🇷", code:"kr", answer:"Südkorea",         aliases:["south korea","korea"],    category:"Flaggenrätsel", difficulty:"easy" },
  { id:4051, type:"flag", flag:"🇮🇳", code:"in", answer:"Indien",           aliases:["india"],                  category:"Flaggenrätsel", difficulty:"easy" },
  { id:4052, type:"flag", flag:"🇹🇭", code:"th", answer:"Thailand",         aliases:[],                         category:"Flaggenrätsel", difficulty:"easy" },
  { id:4053, type:"flag", flag:"🇻🇳", code:"vn", answer:"Vietnam",          aliases:[],                         category:"Flaggenrätsel", difficulty:"medium" },
  { id:4054, type:"flag", flag:"🇮🇩", code:"id", answer:"Indonesien",       aliases:["indonesia"],              category:"Flaggenrätsel", difficulty:"medium" },
  { id:4055, type:"flag", flag:"🇲🇾", code:"my", answer:"Malaysia",         aliases:[],                         category:"Flaggenrätsel", difficulty:"medium" },
  { id:4056, type:"flag", flag:"🇸🇬", code:"sg", answer:"Singapur",         aliases:["singapore"],              category:"Flaggenrätsel", difficulty:"medium" },
  { id:4057, type:"flag", flag:"🇵🇭", code:"ph", answer:"Philippinen",      aliases:["philippines"],            category:"Flaggenrätsel", difficulty:"medium" },
  { id:4058, type:"flag", flag:"🇵🇰", code:"pk", answer:"Pakistan",         aliases:[],                         category:"Flaggenrätsel", difficulty:"medium" },
  { id:4059, type:"flag", flag:"🇧🇩", code:"bd", answer:"Bangladesch",      aliases:["bangladesh"],             category:"Flaggenrätsel", difficulty:"medium" },
  { id:4060, type:"flag", flag:"🇸🇦", code:"sa", answer:"Saudi-Arabien",    aliases:["saudi arabia"],           category:"Flaggenrätsel", difficulty:"medium" },
  { id:4061, type:"flag", flag:"🇦🇪", code:"ae", answer:"Vereinigte Arabische Emirate",aliases:["vae","uae","emirate"], category:"Flaggenrätsel", difficulty:"medium" },
  { id:4062, type:"flag", flag:"🇮🇱", code:"il", answer:"Israel",           aliases:[],                         category:"Flaggenrätsel", difficulty:"medium" },
  { id:4063, type:"flag", flag:"🇮🇷", code:"ir", answer:"Iran",             aliases:[],                         category:"Flaggenrätsel", difficulty:"medium" },
  { id:4064, type:"flag", flag:"🇮🇶", code:"iq", answer:"Irak",             aliases:["iraq"],                   category:"Flaggenrätsel", difficulty:"medium" },
  { id:4065, type:"flag", flag:"🇶🇦", code:"qa", answer:"Katar",            aliases:["qatar"],                  category:"Flaggenrätsel", difficulty:"medium" },
  { id:4066, type:"flag", flag:"🇰🇼", code:"kw", answer:"Kuwait",           aliases:[],                         category:"Flaggenrätsel", difficulty:"hard" },
  { id:4067, type:"flag", flag:"🇯🇴", code:"jo", answer:"Jordanien",        aliases:["jordan"],                 category:"Flaggenrätsel", difficulty:"hard" },
  { id:4068, type:"flag", flag:"🇱🇧", code:"lb", answer:"Libanon",          aliases:["lebanon"],                category:"Flaggenrätsel", difficulty:"hard" },
  { id:4069, type:"flag", flag:"🇸🇾", code:"sy", answer:"Syrien",           aliases:["syria"],                  category:"Flaggenrätsel", difficulty:"hard" },
  { id:4070, type:"flag", flag:"🇾🇪", code:"ye", answer:"Jemen",            aliases:["yemen"],                  category:"Flaggenrätsel", difficulty:"hard" },
  { id:4071, type:"flag", flag:"🇴🇲", code:"om", answer:"Oman",             aliases:[],                         category:"Flaggenrätsel", difficulty:"hard" },
  { id:4072, type:"flag", flag:"🇧🇭", code:"bh", answer:"Bahrain",          aliases:[],                         category:"Flaggenrätsel", difficulty:"hard" },
  { id:4073, type:"flag", flag:"🇦🇫", code:"af", answer:"Afghanistan",      aliases:[],                         category:"Flaggenrätsel", difficulty:"medium" },
  { id:4074, type:"flag", flag:"🇰🇿", code:"kz", answer:"Kasachstan",       aliases:["kazakhstan"],             category:"Flaggenrätsel", difficulty:"medium" },
  { id:4075, type:"flag", flag:"🇺🇿", code:"uz", answer:"Usbekistan",       aliases:["uzbekistan"],             category:"Flaggenrätsel", difficulty:"hard" },
  { id:4076, type:"flag", flag:"🇲🇳", code:"mn", answer:"Mongolei",         aliases:["mongolia"],               category:"Flaggenrätsel", difficulty:"medium" },
  { id:4077, type:"flag", flag:"🇳🇵", code:"np", answer:"Nepal",            aliases:[],                         category:"Flaggenrätsel", difficulty:"medium" },
  { id:4078, type:"flag", flag:"🇱🇰", code:"lk", answer:"Sri Lanka",        aliases:[],                         category:"Flaggenrätsel", difficulty:"medium" },
  { id:4079, type:"flag", flag:"🇲🇲", code:"mm", answer:"Myanmar",          aliases:["burma"],                  category:"Flaggenrätsel", difficulty:"hard" },
  { id:4080, type:"flag", flag:"🇰🇭", code:"kh", answer:"Kambodscha",       aliases:["cambodia"],               category:"Flaggenrätsel", difficulty:"medium" },
  { id:4081, type:"flag", flag:"🇱🇦", code:"la", answer:"Laos",            aliases:[],                         category:"Flaggenrätsel", difficulty:"hard" },
  { id:4082, type:"flag", flag:"🇹🇼", code:"tw", answer:"Taiwan",          aliases:[],                         category:"Flaggenrätsel", difficulty:"medium" },
  { id:4083, type:"flag", flag:"🇰🇵", code:"kp", answer:"Nordkorea",        aliases:["north korea"],            category:"Flaggenrätsel", difficulty:"medium" },
  { id:4084, type:"flag", flag:"🇧🇹", code:"bt", answer:"Bhutan",          aliases:[],                         category:"Flaggenrätsel", difficulty:"hard" },
  { id:4085, type:"flag", flag:"🇧🇳", code:"bn", answer:"Brunei",          aliases:[],                         category:"Flaggenrätsel", difficulty:"hard" },
  { id:4086, type:"flag", flag:"🇹🇱", code:"tl", answer:"Osttimor",         aliases:["timor-leste","timor leste"], category:"Flaggenrätsel", difficulty:"hard" },
  { id:4087, type:"flag", flag:"🇰🇬", code:"kg", answer:"Kirgisistan",      aliases:["kyrgyzstan"],             category:"Flaggenrätsel", difficulty:"hard" },
  { id:4088, type:"flag", flag:"🇹🇯", code:"tj", answer:"Tadschikistan",    aliases:["tajikistan"],             category:"Flaggenrätsel", difficulty:"hard" },
  { id:4089, type:"flag", flag:"🇹🇲", code:"tm", answer:"Turkmenistan",     aliases:[],                         category:"Flaggenrätsel", difficulty:"hard" },
  { id:4090, type:"flag", flag:"🇵🇸", code:"ps", answer:"Palästina",        aliases:["palestine"],              category:"Flaggenrätsel", difficulty:"medium" },
  { id:4091, type:"flag", flag:"🇬🇪", code:"ge", answer:"Georgien",         aliases:["georgia"],                category:"Flaggenrätsel", difficulty:"hard" },
  { id:4092, type:"flag", flag:"🇦🇲", code:"am", answer:"Armenien",         aliases:["armenia"],                category:"Flaggenrätsel", difficulty:"hard" },
  { id:4093, type:"flag", flag:"🇦🇿", code:"az", answer:"Aserbaidschan",    aliases:["azerbaijan"],             category:"Flaggenrätsel", difficulty:"hard" },
  { id:4094, type:"flag", flag:"🇲🇻", code:"mv", answer:"Maldiven",         aliases:["maldives"],               category:"Flaggenrätsel", difficulty:"hard" },

  // ══ AFRIKA ══
  { id:4095, type:"flag", flag:"🇪🇬", code:"eg", answer:"Ägypten",          aliases:["egypt"],                  category:"Flaggenrätsel", difficulty:"easy" },
  { id:4096, type:"flag", flag:"🇿🇦", code:"za", answer:"Südafrika",        aliases:["south africa"],           category:"Flaggenrätsel", difficulty:"easy" },
  { id:4097, type:"flag", flag:"🇳🇬", code:"ng", answer:"Nigeria",          aliases:[],                         category:"Flaggenrätsel", difficulty:"medium" },
  { id:4098, type:"flag", flag:"🇰🇪", code:"ke", answer:"Kenia",            aliases:["kenya"],                  category:"Flaggenrätsel", difficulty:"medium" },
  { id:4099, type:"flag", flag:"🇲🇦", code:"ma", answer:"Marokko",          aliases:["morocco"],                category:"Flaggenrätsel", difficulty:"medium" },
  { id:4100, type:"flag", flag:"🇹🇳", code:"tn", answer:"Tunesien",         aliases:["tunisia"],                category:"Flaggenrätsel", difficulty:"medium" },
  { id:4101, type:"flag", flag:"🇩🇿", code:"dz", answer:"Algerien",         aliases:["algeria"],                category:"Flaggenrätsel", difficulty:"medium" },
  { id:4102, type:"flag", flag:"🇱🇾", code:"ly", answer:"Libyen",           aliases:["libya"],                  category:"Flaggenrätsel", difficulty:"hard" },
  { id:4103, type:"flag", flag:"🇪🇹", code:"et", answer:"Äthiopien",        aliases:["ethiopia"],               category:"Flaggenrätsel", difficulty:"medium" },
  { id:4104, type:"flag", flag:"🇬🇭", code:"gh", answer:"Ghana",            aliases:[],                         category:"Flaggenrätsel", difficulty:"medium" },
  { id:4105, type:"flag", flag:"🇸🇳", code:"sn", answer:"Senegal",          aliases:[],                         category:"Flaggenrätsel", difficulty:"hard" },
  { id:4106, type:"flag", flag:"🇨🇮", code:"ci", answer:"Elfenbeinküste",   aliases:["ivory coast","côte d'ivoire"], category:"Flaggenrätsel", difficulty:"hard" },
  { id:4107, type:"flag", flag:"🇨🇲", code:"cm", answer:"Kamerun",          aliases:["cameroon"],               category:"Flaggenrätsel", difficulty:"hard" },
  { id:4108, type:"flag", flag:"🇺🇬", code:"ug", answer:"Uganda",           aliases:[],                         category:"Flaggenrätsel", difficulty:"hard" },
  { id:4109, type:"flag", flag:"🇹🇿", code:"tz", answer:"Tansania",         aliases:["tanzania"],               category:"Flaggenrätsel", difficulty:"hard" },
  { id:4110, type:"flag", flag:"🇿🇼", code:"zw", answer:"Simbabwe",         aliases:["zimbabwe"],               category:"Flaggenrätsel", difficulty:"hard" },
  { id:4111, type:"flag", flag:"🇿🇲", code:"zm", answer:"Sambia",           aliases:["zambia"],                 category:"Flaggenrätsel", difficulty:"hard" },
  { id:4112, type:"flag", flag:"🇲🇿", code:"mz", answer:"Mosambik",         aliases:["mozambique"],             category:"Flaggenrätsel", difficulty:"hard" },
  { id:4113, type:"flag", flag:"🇦🇴", code:"ao", answer:"Angola",           aliases:[],                         category:"Flaggenrätsel", difficulty:"hard" },
  { id:4114, type:"flag", flag:"🇳🇦", code:"na", answer:"Namibia",          aliases:[],                         category:"Flaggenrätsel", difficulty:"hard" },
  { id:4115, type:"flag", flag:"🇧🇼", code:"bw", answer:"Botswana",         aliases:[],                         category:"Flaggenrätsel", difficulty:"hard" },
  { id:4116, type:"flag", flag:"🇷🇼", code:"rw", answer:"Ruanda",           aliases:["rwanda"],                 category:"Flaggenrätsel", difficulty:"hard" },
  { id:4117, type:"flag", flag:"🇸🇩", code:"sd", answer:"Sudan",            aliases:[],                         category:"Flaggenrätsel", difficulty:"hard" },
  { id:4118, type:"flag", flag:"🇸🇸", code:"ss", answer:"Südsudan",         aliases:["south sudan"],            category:"Flaggenrätsel", difficulty:"hard" },
  { id:4119, type:"flag", flag:"🇨🇩", code:"cd", answer:"Demokratische Republik Kongo",aliases:["dr kongo","kongo","drc"], category:"Flaggenrätsel", difficulty:"hard" },
  { id:4120, type:"flag", flag:"🇨🇬", code:"cg", answer:"Kongo-Brazzaville",aliases:["kongo republik","republic of congo"], category:"Flaggenrätsel", difficulty:"hard" },
  { id:4121, type:"flag", flag:"🇬🇦", code:"ga", answer:"Gabun",            aliases:["gabon"],                  category:"Flaggenrätsel", difficulty:"hard" },
  { id:4122, type:"flag", flag:"🇲🇱", code:"ml", answer:"Mali",             aliases:[],                         category:"Flaggenrätsel", difficulty:"hard" },
  { id:4123, type:"flag", flag:"🇧🇫", code:"bf", answer:"Burkina Faso",     aliases:[],                         category:"Flaggenrätsel", difficulty:"hard" },
  { id:4124, type:"flag", flag:"🇳🇪", code:"ne", answer:"Niger",            aliases:[],                         category:"Flaggenrätsel", difficulty:"hard" },
  { id:4125, type:"flag", flag:"🇹🇩", code:"td", answer:"Tschad",           aliases:["chad"],                   category:"Flaggenrätsel", difficulty:"hard" },
  { id:4126, type:"flag", flag:"🇪🇷", code:"er", answer:"Eritrea",          aliases:[],                         category:"Flaggenrätsel", difficulty:"hard" },
  { id:4127, type:"flag", flag:"🇸🇴", code:"so", answer:"Somalia",          aliases:[],                         category:"Flaggenrätsel", difficulty:"hard" },
  { id:4128, type:"flag", flag:"🇩🇯", code:"dj", answer:"Dschibuti",        aliases:["djibouti"],               category:"Flaggenrätsel", difficulty:"hard" },
  { id:4129, type:"flag", flag:"🇱🇸", code:"ls", answer:"Lesotho",          aliases:[],                         category:"Flaggenrätsel", difficulty:"hard" },
  { id:4130, type:"flag", flag:"🇸🇿", code:"sz", answer:"Eswatini",         aliases:["swasiland","swaziland"],  category:"Flaggenrätsel", difficulty:"hard" },
  { id:4131, type:"flag", flag:"🇲🇼", code:"mw", answer:"Malawi",           aliases:[],                         category:"Flaggenrätsel", difficulty:"hard" },
  { id:4132, type:"flag", flag:"🇧🇮", code:"bi", answer:"Burundi",          aliases:[],                         category:"Flaggenrätsel", difficulty:"hard" },
  { id:4133, type:"flag", flag:"🇧🇯", code:"bj", answer:"Benin",            aliases:[],                         category:"Flaggenrätsel", difficulty:"hard" },
  { id:4134, type:"flag", flag:"🇹🇬", code:"tg", answer:"Togo",             aliases:[],                         category:"Flaggenrätsel", difficulty:"hard" },
  { id:4135, type:"flag", flag:"🇬🇳", code:"gn", answer:"Guinea",           aliases:[],                         category:"Flaggenrätsel", difficulty:"hard" },
  { id:4136, type:"flag", flag:"🇲🇬", code:"mg", answer:"Madagaskar",       aliases:["madagascar"],             category:"Flaggenrätsel", difficulty:"medium" },
  { id:4137, type:"flag", flag:"🇲🇺", code:"mu", answer:"Mauritius",        aliases:[],                         category:"Flaggenrätsel", difficulty:"hard" },
  { id:4138, type:"flag", flag:"🇸🇨", code:"sc", answer:"Seychellen",       aliases:["seychelles"],             category:"Flaggenrätsel", difficulty:"hard" },
  { id:4139, type:"flag", flag:"🇨🇻", code:"cv", answer:"Kap Verde",        aliases:["cabo verde","cape verde"], category:"Flaggenrätsel", difficulty:"hard" },
  { id:4140, type:"flag", flag:"🇬🇲", code:"gm", answer:"Gambia",           aliases:[],                         category:"Flaggenrätsel", difficulty:"hard" },
  { id:4141, type:"flag", flag:"🇬🇼", code:"gw", answer:"Guinea-Bissau",    aliases:[],                         category:"Flaggenrätsel", difficulty:"hard" },
  { id:4142, type:"flag", flag:"🇱🇷", code:"lr", answer:"Liberia",          aliases:[],                         category:"Flaggenrätsel", difficulty:"hard" },
  { id:4143, type:"flag", flag:"🇸🇱", code:"sl", answer:"Sierra Leone",     aliases:[],                         category:"Flaggenrätsel", difficulty:"hard" },
  { id:4144, type:"flag", flag:"🇲🇷", code:"mr", answer:"Mauretanien",      aliases:["mauritania"],             category:"Flaggenrätsel", difficulty:"hard" },
  { id:4145, type:"flag", flag:"🇨🇫", code:"cf", answer:"Zentralafrikanische Republik",aliases:["zar"],         category:"Flaggenrätsel", difficulty:"hard" },
  { id:4146, type:"flag", flag:"🇬🇶", code:"gq", answer:"Äquatorialguinea", aliases:["equatorial guinea"],      category:"Flaggenrätsel", difficulty:"hard" },
  { id:4147, type:"flag", flag:"🇰🇲", code:"km", answer:"Komoren",          aliases:["comoros"],                category:"Flaggenrätsel", difficulty:"hard" },
  { id:4148, type:"flag", flag:"🇸🇹", code:"st", answer:"São Tomé und Príncipe",aliases:["sao tome"],           category:"Flaggenrätsel", difficulty:"hard" },

  // ══ NORDAMERIKA / KARIBIK ══
  { id:4149, type:"flag", flag:"🇺🇸", code:"us", answer:"USA",              aliases:["vereinigte staaten","america","united states"], category:"Flaggenrätsel", difficulty:"easy" },
  { id:4150, type:"flag", flag:"🇨🇦", code:"ca", answer:"Kanada",           aliases:["canada"],                 category:"Flaggenrätsel", difficulty:"easy" },
  { id:4151, type:"flag", flag:"🇲🇽", code:"mx", answer:"Mexiko",           aliases:["mexico"],                 category:"Flaggenrätsel", difficulty:"easy" },
  { id:4152, type:"flag", flag:"🇨🇺", code:"cu", answer:"Kuba",             aliases:["cuba"],                   category:"Flaggenrätsel", difficulty:"medium" },
  { id:4153, type:"flag", flag:"🇯🇲", code:"jm", answer:"Jamaika",          aliases:["jamaica"],                category:"Flaggenrätsel", difficulty:"medium" },
  { id:4154, type:"flag", flag:"🇭🇹", code:"ht", answer:"Haiti",            aliases:[],                         category:"Flaggenrätsel", difficulty:"medium" },
  { id:4155, type:"flag", flag:"🇩🇴", code:"do", answer:"Dominikanische Republik",aliases:["dominican republic"], category:"Flaggenrätsel", difficulty:"medium" },
  { id:4156, type:"flag", flag:"🇬🇹", code:"gt", answer:"Guatemala",        aliases:[],                         category:"Flaggenrätsel", difficulty:"medium" },
  { id:4157, type:"flag", flag:"🇭🇳", code:"hn", answer:"Honduras",         aliases:[],                         category:"Flaggenrätsel", difficulty:"hard" },
  { id:4158, type:"flag", flag:"🇸🇻", code:"sv", answer:"El Salvador",      aliases:[],                         category:"Flaggenrätsel", difficulty:"hard" },
  { id:4159, type:"flag", flag:"🇳🇮", code:"ni", answer:"Nicaragua",        aliases:[],                         category:"Flaggenrätsel", difficulty:"hard" },
  { id:4160, type:"flag", flag:"🇨🇷", code:"cr", answer:"Costa Rica",       aliases:[],                         category:"Flaggenrätsel", difficulty:"medium" },
  { id:4161, type:"flag", flag:"🇵🇦", code:"pa", answer:"Panama",           aliases:[],                         category:"Flaggenrätsel", difficulty:"medium" },
  { id:4162, type:"flag", flag:"🇧🇸", code:"bs", answer:"Bahamas",          aliases:[],                         category:"Flaggenrätsel", difficulty:"hard" },
  { id:4163, type:"flag", flag:"🇧🇧", code:"bb", answer:"Barbados",         aliases:[],                         category:"Flaggenrätsel", difficulty:"hard" },
  { id:4164, type:"flag", flag:"🇹🇹", code:"tt", answer:"Trinidad und Tobago",aliases:["trinidad"],             category:"Flaggenrätsel", difficulty:"hard" },
  { id:4165, type:"flag", flag:"🇧🇿", code:"bz", answer:"Belize",          aliases:[],                         category:"Flaggenrätsel", difficulty:"hard" },
  { id:4166, type:"flag", flag:"🇬🇩", code:"gd", answer:"Grenada",          aliases:[],                         category:"Flaggenrätsel", difficulty:"hard" },
  { id:4167, type:"flag", flag:"🇱🇨", code:"lc", answer:"St. Lucia",        aliases:["saint lucia"],            category:"Flaggenrätsel", difficulty:"hard" },
  { id:4168, type:"flag", flag:"🇻🇨", code:"vc", answer:"St. Vincent und die Grenadinen",aliases:["saint vincent"], category:"Flaggenrätsel", difficulty:"hard" },
  { id:4169, type:"flag", flag:"🇦🇬", code:"ag", answer:"Antigua und Barbuda",aliases:["antigua"],              category:"Flaggenrätsel", difficulty:"hard" },
  { id:4170, type:"flag", flag:"🇩🇲", code:"dm", answer:"Dominica",         aliases:[],                         category:"Flaggenrätsel", difficulty:"hard" },
  { id:4171, type:"flag", flag:"🇰🇳", code:"kn", answer:"St. Kitts und Nevis",aliases:["saint kitts"],          category:"Flaggenrätsel", difficulty:"hard" },

  // ══ SÜDAMERIKA ══
  { id:4172, type:"flag", flag:"🇧🇷", code:"br", answer:"Brasilien",        aliases:["brazil","brasil"],        category:"Flaggenrätsel", difficulty:"easy" },
  { id:4173, type:"flag", flag:"🇦🇷", code:"ar", answer:"Argentinien",      aliases:["argentina"],              category:"Flaggenrätsel", difficulty:"easy" },
  { id:4174, type:"flag", flag:"🇨🇱", code:"cl", answer:"Chile",            aliases:[],                         category:"Flaggenrätsel", difficulty:"easy" },
  { id:4175, type:"flag", flag:"🇨🇴", code:"co", answer:"Kolumbien",        aliases:["colombia"],               category:"Flaggenrätsel", difficulty:"medium" },
  { id:4176, type:"flag", flag:"🇵🇪", code:"pe", answer:"Peru",             aliases:[],                         category:"Flaggenrätsel", difficulty:"medium" },
  { id:4177, type:"flag", flag:"🇻🇪", code:"ve", answer:"Venezuela",        aliases:[],                         category:"Flaggenrätsel", difficulty:"medium" },
  { id:4178, type:"flag", flag:"🇪🇨", code:"ec", answer:"Ecuador",          aliases:[],                         category:"Flaggenrätsel", difficulty:"medium" },
  { id:4179, type:"flag", flag:"🇧🇴", code:"bo", answer:"Bolivien",         aliases:["bolivia"],                category:"Flaggenrätsel", difficulty:"medium" },
  { id:4180, type:"flag", flag:"🇵🇾", code:"py", answer:"Paraguay",         aliases:[],                         category:"Flaggenrätsel", difficulty:"hard" },
  { id:4181, type:"flag", flag:"🇺🇾", code:"uy", answer:"Uruguay",          aliases:[],                         category:"Flaggenrätsel", difficulty:"medium" },
  { id:4182, type:"flag", flag:"🇬🇾", code:"gy", answer:"Guyana",           aliases:[],                         category:"Flaggenrätsel", difficulty:"hard" },
  { id:4183, type:"flag", flag:"🇸🇷", code:"sr", answer:"Suriname",         aliases:[],                         category:"Flaggenrätsel", difficulty:"hard" },

  // ══ OZEANIEN ══
  { id:4184, type:"flag", flag:"🇦🇺", code:"au", answer:"Australien",      aliases:["australia"],              category:"Flaggenrätsel", difficulty:"easy" },
  { id:4185, type:"flag", flag:"🇳🇿", code:"nz", answer:"Neuseeland",       aliases:["new zealand"],            category:"Flaggenrätsel", difficulty:"easy" },
  { id:4186, type:"flag", flag:"🇫🇯", code:"fj", answer:"Fidschi",          aliases:["fiji"],                   category:"Flaggenrätsel", difficulty:"medium" },
  { id:4187, type:"flag", flag:"🇵🇬", code:"pg", answer:"Papua-Neuguinea",  aliases:["papua new guinea"],       category:"Flaggenrätsel", difficulty:"hard" },
  { id:4188, type:"flag", flag:"🇸🇧", code:"sb", answer:"Salomonen",        aliases:["solomon islands"],        category:"Flaggenrätsel", difficulty:"hard" },
  { id:4189, type:"flag", flag:"🇻🇺", code:"vu", answer:"Vanuatu",          aliases:[],                         category:"Flaggenrätsel", difficulty:"hard" },
  { id:4190, type:"flag", flag:"🇼🇸", code:"ws", answer:"Samoa",            aliases:[],                         category:"Flaggenrätsel", difficulty:"hard" },
  { id:4191, type:"flag", flag:"🇹🇴", code:"to", answer:"Tonga",            aliases:[],                         category:"Flaggenrätsel", difficulty:"hard" },
  { id:4192, type:"flag", flag:"🇰🇮", code:"ki", answer:"Kiribati",         aliases:[],                         category:"Flaggenrätsel", difficulty:"hard" },
  { id:4193, type:"flag", flag:"🇫🇲", code:"fm", answer:"Mikronesien",      aliases:["micronesia"],             category:"Flaggenrätsel", difficulty:"hard" },
  { id:4194, type:"flag", flag:"🇵🇼", code:"pw", answer:"Palau",            aliases:[],                         category:"Flaggenrätsel", difficulty:"hard" },
  { id:4195, type:"flag", flag:"🇲🇭", code:"mh", answer:"Marshallinseln",   aliases:["marshall islands"],       category:"Flaggenrätsel", difficulty:"hard" },
];
