// ╔══════════════════════════════════════════════════════╗
// ║  QuizNight – LOGOS-RÄTSEL Modus                       ║
// ║  Wie Flaggenrätsel: Buzzern → Markenname eingeben    ║
// ║  Logo-Bild kommt per Domain von einer Logo-CDN       ║
// ║  IDs 6001–6060                                       ║
// ╚══════════════════════════════════════════════════════╝

export interface LogoQuestion {
  id: number; type: "logo";
  domain: string; // z.B. "nike.com" – für die Logo-Bildquelle
  answer: string; aliases?: string[];
  category: string; difficulty: "easy"|"medium"|"hard";
}

export const LOGO_QUESTIONS: LogoQuestion[] = [
  // ── LEICHT ──────────────────────────────────────────────
  { id:6001, type:"logo", domain:"nike.com",        answer:"Nike",        aliases:[],                  category:"Logos", difficulty:"easy" },
  { id:6002, type:"logo", domain:"apple.com",       answer:"Apple",       aliases:[],                  category:"Logos", difficulty:"easy" },
  { id:6003, type:"logo", domain:"mcdonalds.com",   answer:"McDonald's",  aliases:["mcdonalds","mc donalds"], category:"Logos", difficulty:"easy" },
  { id:6004, type:"logo", domain:"adidas.com",      answer:"Adidas",      aliases:[],                  category:"Logos", difficulty:"easy" },
  { id:6005, type:"logo", domain:"coca-cola.com",   answer:"Coca-Cola",   aliases:["coke","cocacola"], category:"Logos", difficulty:"easy" },
  { id:6006, type:"logo", domain:"google.com",      answer:"Google",      aliases:[],                  category:"Logos", difficulty:"easy" },
  { id:6007, type:"logo", domain:"netflix.com",     answer:"Netflix",     aliases:[],                  category:"Logos", difficulty:"easy" },
  { id:6008, type:"logo", domain:"spotify.com",     answer:"Spotify",     aliases:[],                  category:"Logos", difficulty:"easy" },
  { id:6009, type:"logo", domain:"amazon.com",      answer:"Amazon",      aliases:[],                  category:"Logos", difficulty:"easy" },
  { id:6010, type:"logo", domain:"youtube.com",     answer:"YouTube",     aliases:["you tube"],        category:"Logos", difficulty:"easy" },
  { id:6011, type:"logo", domain:"instagram.com",   answer:"Instagram",   aliases:["insta"],           category:"Logos", difficulty:"easy" },
  { id:6012, type:"logo", domain:"playstation.com", answer:"PlayStation", aliases:["ps","play station"], category:"Logos", difficulty:"easy" },
  { id:6013, type:"logo", domain:"bmw.com",         answer:"BMW",         aliases:[],                  category:"Logos", difficulty:"easy" },
  { id:6014, type:"logo", domain:"ferrari.com",     answer:"Ferrari",     aliases:[],                  category:"Logos", difficulty:"easy" },
  { id:6015, type:"logo", domain:"redbull.com",     answer:"Red Bull",    aliases:["redbull"],         category:"Logos", difficulty:"easy" },
  { id:6016, type:"logo", domain:"starbucks.com",   answer:"Starbucks",   aliases:[],                  category:"Logos", difficulty:"easy" },
  { id:6017, type:"logo", domain:"ikea.com",        answer:"Ikea",        aliases:["ikea möbel"],      category:"Logos", difficulty:"easy" },
  { id:6018, type:"logo", domain:"lego.com",        answer:"Lego",        aliases:[],                  category:"Logos", difficulty:"easy" },
  { id:6019, type:"logo", domain:"puma.com",        answer:"Puma",        aliases:[],                  category:"Logos", difficulty:"easy" },
  { id:6020, type:"logo", domain:"tesla.com",       answer:"Tesla",       aliases:[],                  category:"Logos", difficulty:"easy" },

  // ── MITTEL ──────────────────────────────────────────────
  { id:6021, type:"logo", domain:"mercedes-benz.com",answer:"Mercedes-Benz",aliases:["mercedes","benz"], category:"Logos", difficulty:"medium" },
  { id:6022, type:"logo", domain:"audi.com",        answer:"Audi",        aliases:[],                  category:"Logos", difficulty:"medium" },
  { id:6023, type:"logo", domain:"samsung.com",     answer:"Samsung",     aliases:[],                  category:"Logos", difficulty:"medium" },
  { id:6024, type:"logo", domain:"sony.com",        answer:"Sony",        aliases:[],                  category:"Logos", difficulty:"medium" },
  { id:6025, type:"logo", domain:"nintendo.com",    answer:"Nintendo",    aliases:[],                  category:"Logos", difficulty:"medium" },
  { id:6026, type:"logo", domain:"underarmour.com", answer:"Under Armour",aliases:["underarmour"],     category:"Logos", difficulty:"medium" },
  { id:6027, type:"logo", domain:"levis.com",       answer:"Levi's",      aliases:["levis"],           category:"Logos", difficulty:"medium" },
  { id:6028, type:"logo", domain:"zara.com",        answer:"Zara",        aliases:[],                  category:"Logos", difficulty:"medium" },
  { id:6029, type:"logo", domain:"hm.com",          answer:"H&M",         aliases:["h und m","hm"],    category:"Logos", difficulty:"medium" },
  { id:6030, type:"logo", domain:"burgerking.com",  answer:"Burger King", aliases:["burgerking"],      category:"Logos", difficulty:"medium" },
  { id:6031, type:"logo", domain:"kfc.com",         answer:"KFC",         aliases:["kentucky fried chicken"], category:"Logos", difficulty:"medium" },
  { id:6032, type:"logo", domain:"subway.com",      answer:"Subway",      aliases:[],                  category:"Logos", difficulty:"medium" },
  { id:6033, type:"logo", domain:"dominos.com",     answer:"Domino's",    aliases:["dominos","dominos pizza"], category:"Logos", difficulty:"medium" },
  { id:6034, type:"logo", domain:"paypal.com",      answer:"PayPal",      aliases:["paypal"],          category:"Logos", difficulty:"medium" },
  { id:6035, type:"logo", domain:"uber.com",        answer:"Uber",        aliases:[],                  category:"Logos", difficulty:"medium" },
  { id:6036, type:"logo", domain:"airbnb.com",      answer:"Airbnb",      aliases:["air bnb"],         category:"Logos", difficulty:"medium" },
  { id:6037, type:"logo", domain:"snapchat.com",    answer:"Snapchat",    aliases:["snap"],            category:"Logos", difficulty:"medium" },
  { id:6038, type:"logo", domain:"tiktok.com",      answer:"TikTok",      aliases:["tik tok"],         category:"Logos", difficulty:"medium" },
  { id:6039, type:"logo", domain:"discord.com",     answer:"Discord",     aliases:[],                  category:"Logos", difficulty:"medium" },
  { id:6040, type:"logo", domain:"twitch.tv",       answer:"Twitch",      aliases:[],                  category:"Logos", difficulty:"medium" },

  // ── SCHWER ──────────────────────────────────────────────
  { id:6041, type:"logo", domain:"porsche.com",     answer:"Porsche",     aliases:[],                  category:"Logos", difficulty:"hard" },
  { id:6042, type:"logo", domain:"volkswagen.com",  answer:"Volkswagen",  aliases:["vw"],               category:"Logos", difficulty:"hard" },
  { id:6043, type:"logo", domain:"gucci.com",       answer:"Gucci",       aliases:[],                  category:"Logos", difficulty:"hard" },
  { id:6044, type:"logo", domain:"chanel.com",      answer:"Chanel",      aliases:[],                  category:"Logos", difficulty:"hard" },
  { id:6045, type:"logo", domain:"rolex.com",       answer:"Rolex",       aliases:[],                  category:"Logos", difficulty:"hard" },
  { id:6046, type:"logo", domain:"lufthansa.com",   answer:"Lufthansa",   aliases:[],                  category:"Logos", difficulty:"hard" },
  { id:6047, type:"logo", domain:"emirates.com",    answer:"Emirates",    aliases:[],                  category:"Logos", difficulty:"hard" },
  { id:6048, type:"logo", domain:"fedex.com",       answer:"FedEx",       aliases:["fedex"],           category:"Logos", difficulty:"hard" },
  { id:6049, type:"logo", domain:"dhl.com",         answer:"DHL",         aliases:[],                  category:"Logos", difficulty:"hard" },
  { id:6050, type:"logo", domain:"shell.com",       answer:"Shell",       aliases:[],                  category:"Logos", difficulty:"hard" },
  { id:6051, type:"logo", domain:"nestle.com",      answer:"Nestlé",      aliases:["nestle"],           category:"Logos", difficulty:"hard" },
  { id:6052, type:"logo", domain:"danone.com",      answer:"Danone",      aliases:[],                  category:"Logos", difficulty:"hard" },
  { id:6053, type:"logo", domain:"alibaba.com",     answer:"Alibaba",     aliases:[],                  category:"Logos", difficulty:"hard" },
  { id:6054, type:"logo", domain:"ebay.com",        answer:"eBay",        aliases:["ebay"],            category:"Logos", difficulty:"hard" },
  { id:6055, type:"logo", domain:"visa.com",        answer:"Visa",        aliases:[],                  category:"Logos", difficulty:"hard" },
  { id:6056, type:"logo", domain:"mastercard.com",  answer:"Mastercard",  aliases:["master card"],     category:"Logos", difficulty:"hard" },
  { id:6057, type:"logo", domain:"toyota.com",      answer:"Toyota",      aliases:[],                  category:"Logos", difficulty:"hard" },
  { id:6058, type:"logo", domain:"honda.com",       answer:"Honda",       aliases:[],                  category:"Logos", difficulty:"hard" },
  { id:6059, type:"logo", domain:"ford.com",        answer:"Ford",        aliases:[],                  category:"Logos", difficulty:"hard" },
  { id:6060, type:"logo", domain:"bp.com",          answer:"BP",          aliases:["british petroleum"], category:"Logos", difficulty:"hard" },

  // ── ZUSATZ-RUNDE: weitere 90 Marken über mehr Branchen ──
  // LEICHT
  { id:6061, type:"logo", domain:"facebook.com",    answer:"Facebook",    aliases:["fb","meta"],       category:"Logos", difficulty:"easy" },
  { id:6062, type:"logo", domain:"whatsapp.com",    answer:"WhatsApp",    aliases:["whats app"],       category:"Logos", difficulty:"easy" },
  { id:6063, type:"logo", domain:"twitter.com",     answer:"Twitter",     aliases:["x"],                category:"Logos", difficulty:"easy" },
  { id:6064, type:"logo", domain:"pinterest.com",   answer:"Pinterest",   aliases:[],                  category:"Logos", difficulty:"easy" },
  { id:6065, type:"logo", domain:"linkedin.com",    answer:"LinkedIn",    aliases:["linked in"],       category:"Logos", difficulty:"easy" },
  { id:6066, type:"logo", domain:"xbox.com",        answer:"Xbox",        aliases:[],                  category:"Logos", difficulty:"easy" },
  { id:6067, type:"logo", domain:"pepsi.com",       answer:"Pepsi",       aliases:[],                  category:"Logos", difficulty:"easy" },
  { id:6068, type:"logo", domain:"fanta.com",       answer:"Fanta",       aliases:[],                  category:"Logos", difficulty:"easy" },
  { id:6069, type:"logo", domain:"sprite.com",      answer:"Sprite",      aliases:[],                  category:"Logos", difficulty:"easy" },
  { id:6070, type:"logo", domain:"haribo.com",      answer:"Haribo",      aliases:[],                  category:"Logos", difficulty:"easy" },
  { id:6071, type:"logo", domain:"oreo.com",        answer:"Oreo",        aliases:[],                  category:"Logos", difficulty:"easy" },
  { id:6072, type:"logo", domain:"nutella.com",     answer:"Nutella",     aliases:[],                  category:"Logos", difficulty:"easy" },
  { id:6073, type:"logo", domain:"milka.de",        answer:"Milka",       aliases:[],                  category:"Logos", difficulty:"easy" },
  { id:6074, type:"logo", domain:"lindt.com",       answer:"Lindt",       aliases:[],                  category:"Logos", difficulty:"easy" },
  { id:6075, type:"logo", domain:"oral-b.com",      answer:"Oral-B",      aliases:["oral b"],          category:"Logos", difficulty:"easy" },
  { id:6076, type:"logo", domain:"colgate.com",     answer:"Colgate",     aliases:[],                  category:"Logos", difficulty:"easy" },
  { id:6077, type:"logo", domain:"gillette.com",    answer:"Gillette",    aliases:[],                  category:"Logos", difficulty:"easy" },
  { id:6078, type:"logo", domain:"dove.com",        answer:"Dove",        aliases:[],                  category:"Logos", difficulty:"easy" },
  { id:6079, type:"logo", domain:"nivea.com",       answer:"Nivea",       aliases:[],                  category:"Logos", difficulty:"easy" },
  { id:6080, type:"logo", domain:"loreal.com",      answer:"L'Oréal",     aliases:["loreal","l'oreal"],category:"Logos", difficulty:"easy" },
  { id:6081, type:"logo", domain:"vans.com",        answer:"Vans",        aliases:[],                  category:"Logos", difficulty:"easy" },
  { id:6082, type:"logo", domain:"converse.com",    answer:"Converse",    aliases:[],                  category:"Logos", difficulty:"easy" },
  { id:6083, type:"logo", domain:"newbalance.com",  answer:"New Balance", aliases:["newbalance"],      category:"Logos", difficulty:"easy" },
  { id:6084, type:"logo", domain:"reebok.com",      answer:"Reebok",      aliases:[],                  category:"Logos", difficulty:"easy" },
  { id:6085, type:"logo", domain:"lays.com",        answer:"Lay's",       aliases:["lays"],            category:"Logos", difficulty:"easy" },
  { id:6086, type:"logo", domain:"pringles.com",    answer:"Pringles",    aliases:[],                  category:"Logos", difficulty:"easy" },
  { id:6088, type:"logo", domain:"sega.com",        answer:"Sega",        aliases:[],                  category:"Logos", difficulty:"easy" },
  { id:6089, type:"logo", domain:"epicgames.com",   answer:"Epic Games",  aliases:["epic"],            category:"Logos", difficulty:"easy" },
  { id:6090, type:"logo", domain:"steampowered.com",answer:"Steam",       aliases:[],                  category:"Logos", difficulty:"easy" },

  // MITTEL
  { id:6091, type:"logo", domain:"asics.com",       answer:"Asics",       aliases:[],                  category:"Logos", difficulty:"medium" },
  { id:6092, type:"logo", domain:"timberland.com",  answer:"Timberland",  aliases:[],                  category:"Logos", difficulty:"medium" },
  { id:6093, type:"logo", domain:"northface.com",   answer:"The North Face",aliases:["north face"],    category:"Logos", difficulty:"medium" },
  { id:6094, type:"logo", domain:"patagonia.com",   answer:"Patagonia",   aliases:[],                  category:"Logos", difficulty:"medium" },
  { id:6095, type:"logo", domain:"columbia.com",    answer:"Columbia",    aliases:[],                  category:"Logos", difficulty:"medium" },
  { id:6096, type:"logo", domain:"calvinklein.com", answer:"Calvin Klein",aliases:["ck"],               category:"Logos", difficulty:"medium" },
  { id:6097, type:"logo", domain:"tommyhilfiger.com",answer:"Tommy Hilfiger",aliases:["tommy"],         category:"Logos", difficulty:"medium" },
  { id:6098, type:"logo", domain:"ralphlauren.com", answer:"Ralph Lauren",aliases:[],                  category:"Logos", difficulty:"medium" },
  { id:6099, type:"logo", domain:"diesel.com",      answer:"Diesel",      aliases:[],                  category:"Logos", difficulty:"medium" },
  { id:6100, type:"logo", domain:"superdry.com",    answer:"Superdry",    aliases:[],                  category:"Logos", difficulty:"medium" },
  { id:6101, type:"logo", domain:"primark.com",     answer:"Primark",     aliases:[],                  category:"Logos", difficulty:"medium" },
  { id:6102, type:"logo", domain:"uniqlo.com",      answer:"Uniqlo",      aliases:[],                  category:"Logos", difficulty:"medium" },
  { id:6103, type:"logo", domain:"aldi.com",        answer:"Aldi",        aliases:[],                  category:"Logos", difficulty:"medium" },
  { id:6104, type:"logo", domain:"lidl.com",        answer:"Lidl",        aliases:[],                  category:"Logos", difficulty:"medium" },
  { id:6105, type:"logo", domain:"rewe.de",         answer:"Rewe",        aliases:[],                  category:"Logos", difficulty:"medium" },
  { id:6106, type:"logo", domain:"edeka.de",        answer:"Edeka",       aliases:[],                  category:"Logos", difficulty:"medium" },
  { id:6107, type:"logo", domain:"deutschepost.de", answer:"Deutsche Post",aliases:["dpd post"],        category:"Logos", difficulty:"medium" },
  { id:6108, type:"logo", domain:"booking.com",     answer:"Booking.com", aliases:["booking"],         category:"Logos", difficulty:"medium" },
  { id:6109, type:"logo", domain:"tripadvisor.com", answer:"TripAdvisor", aliases:["trip advisor"],    category:"Logos", difficulty:"medium" },
  { id:6110, type:"logo", domain:"expedia.com",     answer:"Expedia",     aliases:[],                  category:"Logos", difficulty:"medium" },
  { id:6111, type:"logo", domain:"zalando.de",      answer:"Zalando",     aliases:[],                  category:"Logos", difficulty:"medium" },
  { id:6112, type:"logo", domain:"otto.de",         answer:"Otto",        aliases:[],                  category:"Logos", difficulty:"medium" },
  { id:6113, type:"logo", domain:"wish.com",        answer:"Wish",        aliases:[],                  category:"Logos", difficulty:"medium" },
  { id:6114, type:"logo", domain:"etsy.com",        answer:"Etsy",        aliases:[],                  category:"Logos", difficulty:"medium" },
  { id:6115, type:"logo", domain:"shopify.com",     answer:"Shopify",     aliases:[],                  category:"Logos", difficulty:"medium" },
  { id:6116, type:"logo", domain:"slack.com",       answer:"Slack",       aliases:[],                  category:"Logos", difficulty:"medium" },
  { id:6117, type:"logo", domain:"zoom.us",         answer:"Zoom",        aliases:[],                  category:"Logos", difficulty:"medium" },
  { id:6118, type:"logo", domain:"dropbox.com",     answer:"Dropbox",     aliases:[],                  category:"Logos", difficulty:"medium" },
  { id:6119, type:"logo", domain:"adobe.com",       answer:"Adobe",       aliases:[],                  category:"Logos", difficulty:"medium" },
  { id:6120, type:"logo", domain:"intel.com",       answer:"Intel",       aliases:[],                  category:"Logos", difficulty:"medium" },
  { id:6121, type:"logo", domain:"amd.com",         answer:"AMD",         aliases:[],                  category:"Logos", difficulty:"medium" },
  { id:6122, type:"logo", domain:"nvidia.com",      answer:"Nvidia",      aliases:[],                  category:"Logos", difficulty:"medium" },
  { id:6123, type:"logo", domain:"logitech.com",    answer:"Logitech",    aliases:[],                  category:"Logos", difficulty:"medium" },
  { id:6124, type:"logo", domain:"razer.com",       answer:"Razer",       aliases:[],                  category:"Logos", difficulty:"medium" },
  { id:6125, type:"logo", domain:"corsair.com",     answer:"Corsair",     aliases:[],                  category:"Logos", difficulty:"medium" },
  { id:6126, type:"logo", domain:"garmin.com",      answer:"Garmin",      aliases:[],                  category:"Logos", difficulty:"medium" },
  { id:6127, type:"logo", domain:"gopro.com",       answer:"GoPro",       aliases:["go pro"],          category:"Logos", difficulty:"medium" },
  { id:6128, type:"logo", domain:"canon.com",       answer:"Canon",       aliases:[],                  category:"Logos", difficulty:"medium" },
  { id:6129, type:"logo", domain:"nikon.com",       answer:"Nikon",       aliases:[],                  category:"Logos", difficulty:"medium" },
  { id:6130, type:"logo", domain:"philips.com",     answer:"Philips",     aliases:[],                  category:"Logos", difficulty:"medium" },

  // SCHWER
  { id:6131, type:"logo", domain:"lamborghini.com", answer:"Lamborghini", aliases:[],                  category:"Logos", difficulty:"hard" },
  { id:6132, type:"logo", domain:"maserati.com",    answer:"Maserati",    aliases:[],                  category:"Logos", difficulty:"hard" },
  { id:6133, type:"logo", domain:"bentley.com",     answer:"Bentley",     aliases:[],                  category:"Logos", difficulty:"hard" },
  { id:6134, type:"logo", domain:"rolls-roycemotorcars.com",answer:"Rolls-Royce",aliases:["rolls royce"],category:"Logos", difficulty:"hard" },
  { id:6135, type:"logo", domain:"astonmartin.com", answer:"Aston Martin",aliases:[],                  category:"Logos", difficulty:"hard" },
  { id:6136, type:"logo", domain:"jaguar.com",      answer:"Jaguar",      aliases:[],                  category:"Logos", difficulty:"hard" },
  { id:6137, type:"logo", domain:"landrover.com",   answer:"Land Rover",  aliases:["landrover"],       category:"Logos", difficulty:"hard" },
  { id:6138, type:"logo", domain:"peugeot.com",     answer:"Peugeot",     aliases:[],                  category:"Logos", difficulty:"hard" },
  { id:6139, type:"logo", domain:"citroen.com",     answer:"Citroën",     aliases:["citroen"],         category:"Logos", difficulty:"hard" },
  { id:6140, type:"logo", domain:"renault.com",     answer:"Renault",     aliases:[],                  category:"Logos", difficulty:"hard" },
  { id:6141, type:"logo", domain:"skoda-auto.com",  answer:"Škoda",       aliases:["skoda"],           category:"Logos", difficulty:"hard" },
  { id:6142, type:"logo", domain:"seat.com",        answer:"Seat",        aliases:[],                  category:"Logos", difficulty:"hard" },
  { id:6143, type:"logo", domain:"fiat.com",        answer:"Fiat",        aliases:[],                  category:"Logos", difficulty:"hard" },
  { id:6144, type:"logo", domain:"alfaromeo.com",   answer:"Alfa Romeo",  aliases:["alfa"],            category:"Logos", difficulty:"hard" },
  { id:6145, type:"logo", domain:"cartier.com",     answer:"Cartier",     aliases:[],                  category:"Logos", difficulty:"hard" },
  { id:6146, type:"logo", domain:"louisvuitton.com",answer:"Louis Vuitton",aliases:["lv"],              category:"Logos", difficulty:"hard" },
  { id:6147, type:"logo", domain:"prada.com",       answer:"Prada",       aliases:[],                  category:"Logos", difficulty:"hard" },
  { id:6148, type:"logo", domain:"versace.com",     answer:"Versace",     aliases:[],                  category:"Logos", difficulty:"hard" },
  { id:6149, type:"logo", domain:"hermes.com",      answer:"Hermès",      aliases:["hermes"],          category:"Logos", difficulty:"hard" },
  { id:6150, type:"logo", domain:"dior.com",        answer:"Dior",        aliases:[],                  category:"Logos", difficulty:"hard" },
  { id:6151, type:"logo", domain:"balenciaga.com",  answer:"Balenciaga",  aliases:[],                  category:"Logos", difficulty:"hard" },
  { id:6152, type:"logo", domain:"givenchy.com",    answer:"Givenchy",    aliases:[],                  category:"Logos", difficulty:"hard" },
  { id:6153, type:"logo", domain:"fendi.com",       answer:"Fendi",       aliases:[],                  category:"Logos", difficulty:"hard" },
  { id:6154, type:"logo", domain:"burberry.com",    answer:"Burberry",    aliases:[],                  category:"Logos", difficulty:"hard" },
  { id:6155, type:"logo", domain:"swarovski.com",   answer:"Swarovski",   aliases:[],                  category:"Logos", difficulty:"hard" },
  { id:6156, type:"logo", domain:"tiffany.com",     answer:"Tiffany & Co.",aliases:["tiffany"],        category:"Logos", difficulty:"hard" },
  { id:6157, type:"logo", domain:"goldmansachs.com",answer:"Goldman Sachs",aliases:["goldman"],         category:"Logos", difficulty:"hard" },
  { id:6158, type:"logo", domain:"hsbc.com",        answer:"HSBC",        aliases:[],                  category:"Logos", difficulty:"hard" },
  { id:6159, type:"logo", domain:"db.com",          answer:"Deutsche Bank",aliases:[],                 category:"Logos", difficulty:"hard" },
  { id:6160, type:"logo", domain:"allianz.com",     answer:"Allianz",     aliases:[],                  category:"Logos", difficulty:"hard" },
];
