export interface RankingItem {
  rank: number; answer: string; aliases?: string[]; detail?: string;
}
export interface RankingQuestion {
  id: number; type: "ranking"; title: string; description?: string;
  category: string; items: RankingItem[]; timePerTurn: number;
}

// ╔══════════════════════════════════════════════════════╗
// ║  QuizNight – RANKING Modus (komplett neuer Katalog)  ║
// ║  30 Listen  ·  IDs 3001–3030                        ║
// ╚══════════════════════════════════════════════════════╝

export const RANKING_QUESTIONS: RankingQuestion[] = [
  {
    id:3001, type:"ranking", title:"Top 15 meistgestreamte Animeserien", description:"Nach globaler Streaming-Reichweite", category:"Ranking", timePerTurn:30,
    items:[
      {rank:1,  answer:"Attack on Titan",      aliases:["attack on titan","aot","angriff der titanen"], detail:"weltweiter Hit"},
      {rank:2,  answer:"Demon Slayer",         aliases:["demon slayer","kimetsu no yaiba"],   detail:"Rekord-Kinostart"},
      {rank:3,  answer:"One Piece",            aliases:["one piece"],                          detail:"über 1000 Folgen"},
      {rank:4,  answer:"Naruto",               aliases:["naruto"],                             detail:"Shonen-Klassiker"},
      {rank:5,  answer:"My Hero Academia",     aliases:["my hero academia","boku no hero"],   detail:"Helden-Anime"},
      {rank:6,  answer:"Jujutsu Kaisen",       aliases:["jujutsu kaisen","jjk"],               detail:"Dämonenjäger"},
      {rank:7,  answer:"Death Note",           aliases:["death note"],                         detail:"Psycho-Thriller"},
      {rank:8,  answer:"Dragon Ball Z",        aliases:["dragon ball z","dbz","dragonball"],  detail:"90er Ikone"},
      {rank:9,  answer:"Fullmetal Alchemist",  aliases:["fullmetal alchemist","fma"],          detail:"Alchemie-Saga"},
      {rank:10, answer:"Tokyo Revengers",      aliases:["tokyo revengers"],                    detail:"Zeitreise-Drama"},
      {rank:11, answer:"Spy x Family",         aliases:["spy x family","spy family"],          detail:"Familien-Comedy"},
      {rank:12, answer:"Chainsaw Man",         aliases:["chainsaw man"],                       detail:"Dark Fantasy"},
      {rank:13, answer:"Hunter x Hunter",      aliases:["hunter x hunter","hxh"],               detail:"Abenteuer-Klassiker"},
      {rank:14, answer:"One Punch Man",        aliases:["one punch man","opm"],                 detail:"Parodie-Held"},
      {rank:15, answer:"Bleach",               aliases:["bleach"],                              detail:"Shinigami-Saga"},
    ],
  },
  {
    id:3002, type:"ranking", title:"Top 15 beliebteste Gerichte der Welt", description:"Nach globaler Bekanntheit", category:"Ranking", timePerTurn:30,
    items:[
      {rank:1,  answer:"Pizza",          aliases:[],                  detail:"Italien"},
      {rank:2,  answer:"Sushi",          aliases:[],                  detail:"Japan"},
      {rank:3,  answer:"Burger",         aliases:["hamburger"],       detail:"USA"},
      {rank:4,  answer:"Pasta",          aliases:["nudeln"],          detail:"Italien"},
      {rank:5,  answer:"Tacos",          aliases:[],                  detail:"Mexiko"},
      {rank:6,  answer:"Currywurst",     aliases:[],                  detail:"Deutschland"},
      {rank:7,  answer:"Ramen",          aliases:[],                  detail:"Japan"},
      {rank:8,  answer:"Pad Thai",       aliases:["padthai"],         detail:"Thailand"},
      {rank:9,  answer:"Döner Kebab",    aliases:["döner","kebab"],   detail:"Türkei"},
      {rank:10, answer:"Paella",         aliases:[],                  detail:"Spanien"},
      {rank:11, answer:"Curry",         aliases:[],                  detail:"Indien"},
      {rank:12, answer:"Croissant",      aliases:[],                  detail:"Frankreich/Österreich"},
      {rank:13, answer:"Pho",            aliases:[],                  detail:"Vietnam"},
      {rank:14, answer:"Falafel",        aliases:[],                  detail:"Naher Osten"},
      {rank:15, answer:"Schnitzel",      aliases:["wiener schnitzel"],detail:"Österreich"},
    ],
  },
  {
    id:3003, type:"ranking", title:"Top 15 meistverkaufte Automarken weltweit", description:"Nach Absatz pro Jahr", category:"Ranking", timePerTurn:30,
    items:[
      {rank:1,  answer:"Toyota",      aliases:[], detail:"Japan"},
      {rank:2,  answer:"Volkswagen",  aliases:["vw"], detail:"Deutschland"},
      {rank:3,  answer:"Hyundai",     aliases:[], detail:"Südkorea"},
      {rank:4,  answer:"Ford",        aliases:[], detail:"USA"},
      {rank:5,  answer:"Honda",       aliases:[], detail:"Japan"},
      {rank:6,  answer:"Chevrolet",   aliases:[], detail:"USA"},
      {rank:7,  answer:"Nissan",      aliases:[], detail:"Japan"},
      {rank:8,  answer:"Kia",         aliases:[], detail:"Südkorea"},
      {rank:9,  answer:"BMW",         aliases:[], detail:"Deutschland"},
      {rank:10, answer:"Mercedes-Benz",aliases:["mercedes"], detail:"Deutschland"},
      {rank:11, answer:"Audi",        aliases:[], detail:"Deutschland"},
      {rank:12, answer:"Tesla",       aliases:[], detail:"USA"},
      {rank:13, answer:"Renault",     aliases:[], detail:"Frankreich"},
      {rank:14, answer:"Peugeot",     aliases:[], detail:"Frankreich"},
      {rank:15, answer:"Mazda",       aliases:[], detail:"Japan"},
    ],
  },
  {
    id:3004, type:"ranking", title:"Top 15 berühmteste Gemälde der Kunstgeschichte", description:"Nach weltweiter Bekanntheit", category:"Ranking", timePerTurn:35,
    items:[
      {rank:1,  answer:"Mona Lisa",                aliases:[], detail:"da Vinci"},
      {rank:2,  answer:"Die Sternennacht",         aliases:["sternennacht","starry night"], detail:"van Gogh"},
      {rank:3,  answer:"Der Schrei",                aliases:["the scream"], detail:"Munch"},
      {rank:4,  answer:"Das letzte Abendmahl",      aliases:["last supper"], detail:"da Vinci"},
      {rank:5,  answer:"Mädchen mit dem Perlenohrring",aliases:["girl with a pearl earring"], detail:"Vermeer"},
      {rank:6,  answer:"Guernica",                  aliases:[], detail:"Picasso"},
      {rank:7,  answer:"Die Geburt der Venus",       aliases:["birth of venus"], detail:"Botticelli"},
      {rank:8,  answer:"Der Kuss",                   aliases:["the kiss"], detail:"Klimt"},
      {rank:9,  answer:"Las Meninas",                aliases:[], detail:"Velázquez"},
      {rank:10, answer:"Die Erschaffung Adams",       aliases:["creation of adam"], detail:"Michelangelo"},
      {rank:11, answer:"Nachtwache",                  aliases:["night watch"], detail:"Rembrandt"},
      {rank:12, answer:"Amerikanische Gotik",         aliases:["american gothic"], detail:"Grant Wood"},
      {rank:13, answer:"Die beständigkeit der Erinnerung",aliases:["persistence of memory","schmelzende uhren"], detail:"Dalí"},
      {rank:14, answer:"Wanderer über dem Nebelmeer", aliases:[], detail:"Caspar David Friedrich"},
      {rank:15, answer:"Komposition VIII",            aliases:["composition 8"], detail:"Kandinsky"},
    ],
  },
  {
    id:3005, type:"ranking", title:"Top 15 schnellste Achterbahnen der Welt", description:"Nach Höchstgeschwindigkeit", category:"Ranking", timePerTurn:30,
    items:[
      {rank:1,  answer:"Formula Rossa",        aliases:[], detail:"240 km/h – Abu Dhabi"},
      {rank:2,  answer:"Kingda Ka",            aliases:[], detail:"206 km/h – USA"},
      {rank:3,  answer:"Top Thrill 2",         aliases:["top thrill dragster"], detail:"190 km/h – USA"},
      {rank:4,  answer:"Red Force",            aliases:[], detail:"180 km/h – Spanien"},
      {rank:5,  answer:"Do-Dodonpa",           aliases:[], detail:"180 km/h – Japan"},
      {rank:6,  answer:"Tatsu",                aliases:[], detail:"savage Speed – USA"},
      {rank:7,  answer:"Fury 325",             aliases:[], detail:"153 km/h – USA"},
      {rank:8,  answer:"Steel Dragon 2000",    aliases:[], detail:"153 km/h – Japan"},
      {rank:9,  answer:"Millennium Force",     aliases:[], detail:"150 km/h – USA"},
      {rank:10, answer:"Leviathan",            aliases:[], detail:"148 km/h – Kanada"},
      {rank:11, answer:"Intimidator 305",      aliases:[], detail:"145 km/h – USA"},
      {rank:12, answer:"Goliath",              aliases:[], detail:"true Speed – USA"},
      {rank:13, answer:"Silver Star",          aliases:[], detail:"127 km/h – Deutschland"},
      {rank:14, answer:"Blue Fire Megacoaster",aliases:[], detail:"100 km/h – Deutschland"},
      {rank:15, answer:"Wodan Timbur Coaster", aliases:[], detail:"100 km/h – Deutschland"},
    ],
  },
  {
    id:3006, type:"ranking", title:"Top 10 größte Wüsten der Welt", description:"Nach Fläche", category:"Ranking", timePerTurn:30,
    items:[
      {rank:1,  answer:"Antarktische Wüste",  aliases:["antarktis"],          detail:"14 Mio. km²"},
      {rank:2,  answer:"Arktische Wüste",     aliases:["arktis"],              detail:"13,9 Mio. km²"},
      {rank:3,  answer:"Sahara",              aliases:[],                      detail:"9,2 Mio. km²"},
      {rank:4,  answer:"Arabische Wüste",     aliases:[],                      detail:"2,3 Mio. km²"},
      {rank:5,  answer:"Gobi",                aliases:[],                      detail:"1,3 Mio. km²"},
      {rank:6,  answer:"Kalahari",            aliases:[],                      detail:"900.000 km²"},
      {rank:7,  answer:"Patagonische Wüste",  aliases:["patagonien"],          detail:"670.000 km²"},
      {rank:8,  answer:"Großes Victoriabecken",aliases:["great victoria desert"],detail:"647.000 km²"},
      {rank:9,  answer:"Syrische Wüste",      aliases:[],                      detail:"500.000 km²"},
      {rank:10, answer:"Chihuahua-Wüste",     aliases:[],                      detail:"450.000 km²"},
    ],
  },
  {
    id:3007, type:"ranking", title:"Top 10 höchste Wasserfälle der Welt", description:"Nach Fallhöhe", category:"Ranking", timePerTurn:30,
    items:[
      {rank:1,  answer:"Angel Falls",      aliases:["salto angel"],   detail:"979 m – Venezuela"},
      {rank:2,  answer:"Tugela Falls",     aliases:[],                 detail:"948 m – Südafrika"},
      {rank:3,  answer:"Kukenan Falls",    aliases:[],                 detail:"674 m – Venezuela"},
      {rank:4,  answer:"Yosemite Falls",   aliases:[],                 detail:"739 m – USA"},
      {rank:5,  answer:"Vinnufallet",      aliases:[],                 detail:"865 m – Norwegen"},
      {rank:6,  answer:"Olo'upena Falls",  aliases:[],                 detail:"900 m – Hawaii"},
      {rank:7,  answer:"Pu'uka'oku Falls", aliases:[],                 detail:"840 m – Hawaii"},
      {rank:8,  answer:"James Bruce Falls",aliases:[],                 detail:"840 m – Kanada"},
      {rank:9,  answer:"Browne Falls",     aliases:[],                 detail:"836 m – Neuseeland"},
      {rank:10, answer:"Strand-i-Burda",   aliases:[],                 detail:"800 m – Norwegen"},
    ],
  },
  {
    id:3008, type:"ranking", title:"Top 15 giftigsten Tiere der Welt", description:"Nach Gefährlichkeit für Menschen", category:"Ranking", timePerTurn:30,
    items:[
      {rank:1,  answer:"Würfelqualle",        aliases:["box jellyfish"],  detail:"Australien"},
      {rank:2,  answer:"Inlandtaipan",        aliases:["taipan"],         detail:"giftigste Schlange"},
      {rank:3,  answer:"Blaugeringelter Krake",aliases:["blue ringed octopus"],detail:"kein Gegenmittel"},
      {rank:4,  answer:"Pfeilgiftfrosch",     aliases:["poison dart frog"],detail:"Südamerika"},
      {rank:5,  answer:"Steinfisch",          aliases:["stonefish"],       detail:"gefährlichster Fisch"},
      {rank:6,  answer:"Schwarze Mamba",      aliases:["black mamba"],     detail:"schnellste Schlange"},
      {rank:7,  answer:"Skorpion (Deathstalker)",aliases:["deathstalker"], detail:"Naher Osten"},
      {rank:8,  answer:"Trichternetzspinne",  aliases:["funnel web spider"],detail:"Australien"},
      {rank:9,  answer:"Schwarze Witwe",      aliases:["black widow"],     detail:"weltweit"},
      {rank:10, answer:"Kegelschnecke",       aliases:["cone snail"],      detail:"Meeresschnecke"},
      {rank:11, answer:"Puffotter",           aliases:["puff adder"],      detail:"Afrika"},
      {rank:12, answer:"Kettenviper",         aliases:["russell's viper"], detail:"Asien"},
      {rank:13, answer:"Feuerameise",         aliases:["fire ant"],        detail:"Südamerika"},
      {rank:14, answer:"Skorpionfisch",       aliases:["scorpionfish"],    detail:"Korallenriffe"},
      {rank:15, answer:"Brasilianische Wanderspinne",aliases:["wandering spider"],detail:"Südamerika"},
    ],
  },
  {
    id:3009, type:"ranking", title:"Top 15 teuerste Uhrenmarken der Welt", description:"Nach Markenwert/Prestige", category:"Ranking", timePerTurn:30,
    items:[
      {rank:1,  answer:"Patek Philippe", aliases:[], detail:"Schweiz"},
      {rank:2,  answer:"Rolex",          aliases:[], detail:"Schweiz"},
      {rank:3,  answer:"Audemars Piguet",aliases:[], detail:"Schweiz"},
      {rank:4,  answer:"Richard Mille",  aliases:[], detail:"Schweiz"},
      {rank:5,  answer:"Vacheron Constantin",aliases:[], detail:"Schweiz"},
      {rank:6,  answer:"Jaeger-LeCoultre",aliases:[], detail:"Schweiz"},
      {rank:7,  answer:"IWC",            aliases:[], detail:"Schweiz"},
      {rank:8,  answer:"Breguet",        aliases:[], detail:"Schweiz"},
      {rank:9,  answer:"Omega",          aliases:[], detail:"Schweiz"},
      {rank:10, answer:"Cartier",        aliases:[], detail:"Frankreich"},
      {rank:11, answer:"Piaget",         aliases:[], detail:"Schweiz"},
      {rank:12, answer:"Breitling",      aliases:[], detail:"Schweiz"},
      {rank:13, answer:"TAG Heuer",      aliases:["tag heuer"], detail:"Schweiz"},
      {rank:14, answer:"Hublot",         aliases:[], detail:"Schweiz"},
      {rank:15, answer:"Panerai",        aliases:[], detail:"Italien"},
    ],
  },
  {
    id:3010, type:"ranking", title:"Top 15 meistgespielte Mobile Games aller Zeiten", description:"Nach Downloads", category:"Ranking", timePerTurn:30,
    items:[
      {rank:1,  answer:"Subway Surfers",  aliases:[], detail:"über 1 Mrd. Downloads"},
      {rank:2,  answer:"Candy Crush Saga",aliases:["candy crush"], detail:"über 1 Mrd."},
      {rank:3,  answer:"PUBG Mobile",     aliases:["pubg"], detail:"über 1 Mrd."},
      {rank:4,  answer:"Free Fire",       aliases:[], detail:"über 1 Mrd."},
      {rank:5,  answer:"Among Us",        aliases:[], detail:"über 500 Mio."},
      {rank:6,  answer:"Pokémon GO",      aliases:["pokemon go"], detail:"über 700 Mio."},
      {rank:7,  answer:"Clash of Clans",  aliases:["coc"], detail:"über 700 Mio."},
      {rank:8,  answer:"Roblox",          aliases:[], detail:"über 500 Mio."},
      {rank:9,  answer:"Temple Run",      aliases:["temple run 2"], detail:"über 1 Mrd."},
      {rank:10, answer:"Fruit Ninja",     aliases:[], detail:"über 1 Mrd."},
      {rank:11, answer:"Clash Royale",    aliases:[], detail:"über 500 Mio."},
      {rank:12, answer:"Brawl Stars",     aliases:[], detail:"über 500 Mio."},
      {rank:13, answer:"Angry Birds",     aliases:[], detail:"über 4 Mrd. (Serie)"},
      {rank:14, answer:"8 Ball Pool",     aliases:[], detail:"über 500 Mio."},
      {rank:15, answer:"Minecraft",       aliases:[], detail:"mobile Version"},
    ],
  },
  {
    id:3011, type:"ranking", title:"Top 15 erfolgreichste Boxer der Geschichte", description:"Nach Profi-Bilanz/Titeln", category:"Ranking", timePerTurn:30,
    items:[
      {rank:1,  answer:"Floyd Mayweather", aliases:["mayweather"], detail:"50-0 ungeschlagen"},
      {rank:2,  answer:"Muhammad Ali",     aliases:["ali"],         detail:"3× Weltmeister"},
      {rank:3,  answer:"Mike Tyson",       aliases:["tyson"],       detail:"jüngster Weltmeister"},
      {rank:4,  answer:"Manny Pacquiao",   aliases:["pacquiao"],    detail:"8 Gewichtsklassen"},
      {rank:5,  answer:"Sugar Ray Robinson",aliases:["ray robinson"],detail:"P4P-Legende"},
      {rank:6,  answer:"Joe Louis",        aliases:[],              detail:"12 Jahre Champion"},
      {rank:7,  answer:"Rocky Marciano",   aliases:["marciano"],   detail:"49-0 ungeschlagen"},
      {rank:8,  answer:"Canelo Álvarez",   aliases:["canelo"],     detail:"4 Gewichtsklassen"},
      {rank:9,  answer:"Evander Holyfield",aliases:["holyfield"],  detail:"4× Schwergewicht-Champ"},
      {rank:10, answer:"Lennox Lewis",     aliases:[],              detail:"undisputed Champion"},
      {rank:11, answer:"Roberto Durán",    aliases:["duran"],      detail:"4 Gewichtsklassen"},
      {rank:12, answer:"George Foreman",   aliases:["foreman"],    detail:"ältester Weltmeister"},
      {rank:13, answer:"Julio César Chávez",aliases:["chavez"],     detail:"über 100 Siege"},
      {rank:14, answer:"Oscar De La Hoya", aliases:["de la hoya"], detail:"6 Gewichtsklassen"},
      {rank:15, answer:"Tyson Fury",       aliases:["fury"],       detail:"WBC Champion"},
    ],
  },
  {
    id:3012, type:"ranking", title:"Top 15 meistbesuchte Nationalparks der Welt", description:"Nach Besucherzahl/Jahr", category:"Ranking", timePerTurn:30,
    items:[
      {rank:1,  answer:"Mount Huangshan", aliases:["huangshan"], detail:"China"},
      {rank:2,  answer:"Zion-Nationalpark",aliases:["zion"],     detail:"USA"},
      {rank:3,  answer:"Great Smoky Mountains",aliases:["smoky mountains"],detail:"USA"},
      {rank:4,  answer:"Yellowstone",      aliases:[],            detail:"USA"},
      {rank:5,  answer:"Grand Canyon",     aliases:[],            detail:"USA"},
      {rank:6,  answer:"Krüger-Nationalpark",aliases:["kruger"],  detail:"Südafrika"},
      {rank:7,  answer:"Banff-Nationalpark",aliases:["banff"],    detail:"Kanada"},
      {rank:8,  answer:"Plitvicer Seen",   aliases:["plitvice"],  detail:"Kroatien"},
      {rank:9,  answer:"Serengeti",        aliases:[],            detail:"Tansania"},
      {rank:10, answer:"Yosemite",         aliases:[],            detail:"USA"},
      {rank:11, answer:"Torres del Paine", aliases:[],            detail:"Chile"},
      {rank:12, answer:"Sächsische Schweiz",aliases:[],           detail:"Deutschland"},
      {rank:13, answer:"Lake District",    aliases:[],            detail:"Großbritannien"},
      {rank:14, answer:"Fjordland",        aliases:["fiordland"], detail:"Neuseeland"},
      {rank:15, answer:"Iguazú-Nationalpark",aliases:["iguazu"],   detail:"Argentinien/Brasilien"},
    ],
  },
  {
    id:3013, type:"ranking", title:"Top 15 berühmteste Brücken der Welt", description:"Nach Bekanntheit", category:"Ranking", timePerTurn:30,
    items:[
      {rank:1,  answer:"Golden Gate Bridge", aliases:[], detail:"San Francisco"},
      {rank:2,  answer:"Tower Bridge",       aliases:[], detail:"London"},
      {rank:3,  answer:"Brooklyn Bridge",    aliases:[], detail:"New York"},
      {rank:4,  answer:"Sydney Harbour Bridge",aliases:["harbour bridge"], detail:"Sydney"},
      {rank:5,  answer:"Charles-Brücke",     aliases:["charles bridge","karlsbrücke"], detail:"Prag"},
      {rank:6,  answer:"Ponte Vecchio",      aliases:[], detail:"Florenz"},
      {rank:7,  answer:"Rialtobrücke",       aliases:["rialto bridge"], detail:"Venedig"},
      {rank:8,  answer:"Akashi-Kaikyō-Brücke",aliases:["akashi kaikyo"], detail:"Japan – längste Hängebrücke"},
      {rank:9,  answer:"Millau-Viadukt",      aliases:["millau viaduct"], detail:"Frankreich"},
      {rank:10, answer:"Pont du Gard",        aliases:[], detail:"Frankreich – römisches Aquädukt"},
      {rank:11, answer:"Vasco-da-Gama-Brücke", aliases:["vasco da gama"], detail:"Portugal"},
      {rank:12, answer:"Oresundbrücke",        aliases:["öresundbrücke","oresund bridge"], detail:"Dänemark/Schweden"},
      {rank:13, answer:"Hängebrücke Capilano",  aliases:["capilano bridge"], detail:"Kanada"},
      {rank:14, answer:"Mostar-Brücke",         aliases:["stari most"], detail:"Bosnien"},
      {rank:15, answer:"Magdeburger Wasserbrücke",aliases:["wasserstrassenkreuz magdeburg"], detail:"Deutschland"},
    ],
  },
  {
    id:3014, type:"ranking", title:"Top 15 meistgenutzte Programmiersprachen", description:"Nach Entwickler-Beliebtheit 2024", category:"Ranking", timePerTurn:30,
    items:[
      {rank:1,  answer:"JavaScript", aliases:["js"], detail:"Web-Standard"},
      {rank:2,  answer:"Python",     aliases:[],      detail:"KI & Data Science"},
      {rank:3,  answer:"Java",       aliases:[],      detail:"Enterprise-Sprache"},
      {rank:4,  answer:"TypeScript", aliases:["ts"],  detail:"JS mit Typsicherheit"},
      {rank:5,  answer:"C#",         aliases:["csharp","c sharp"], detail:"Microsoft"},
      {rank:6,  answer:"C++",        aliases:["cpp"], detail:"Performance-Sprache"},
      {rank:7,  answer:"PHP",        aliases:[],      detail:"Web-Backend"},
      {rank:8,  answer:"C",          aliases:[],      detail:"Systemnahe Sprache"},
      {rank:9,  answer:"Swift",      aliases:[],      detail:"Apple/iOS"},
      {rank:10, answer:"Go",         aliases:["golang"], detail:"Google"},
      {rank:11, answer:"Kotlin",     aliases:[],      detail:"Android"},
      {rank:12, answer:"Rust",       aliases:[],      detail:"Speichersicherheit"},
      {rank:13, answer:"Ruby",       aliases:[],      detail:"Rails-Framework"},
      {rank:14, answer:"SQL",        aliases:[],      detail:"Datenbanken"},
      {rank:15, answer:"R",          aliases:[],      detail:"Statistik"},
    ],
  },
  {
    id:3015, type:"ranking", title:"Top 15 höchstdotierte E-Sport-Spiele", description:"Nach Gesamtpreisgeld", category:"Ranking", timePerTurn:30,
    items:[
      {rank:1,  answer:"Dota 2",                aliases:[], detail:"The International"},
      {rank:2,  answer:"Fortnite",              aliases:[], detail:"World Cup"},
      {rank:3,  answer:"League of Legends",     aliases:["lol"], detail:"Worlds"},
      {rank:4,  answer:"PUBG",                  aliases:[], detail:"Battle Royale"},
      {rank:5,  answer:"Counter-Strike",        aliases:["cs","cs2","csgo"], detail:"Majors"},
      {rank:6,  answer:"Arena of Valor",        aliases:[], detail:"Mobile MOBA"},
      {rank:7,  answer:"Free Fire",             aliases:[], detail:"Mobile Battle Royale"},
      {rank:8,  answer:"Overwatch",             aliases:[], detail:"Blizzard"},
      {rank:9,  answer:"Rainbow Six Siege",     aliases:["r6","siege"], detail:"Ubisoft"},
      {rank:10, answer:"Call of Duty",          aliases:["cod"], detail:"Warzone/League"},
      {rank:11, answer:"StarCraft II",          aliases:["starcraft 2","sc2"], detail:"Blizzard Klassiker"},
      {rank:12, answer:"Rocket League",         aliases:[], detail:"Fußball mit Autos"},
      {rank:13, answer:"Valorant",              aliases:[], detail:"Riot Games"},
      {rank:14, answer:"Mobile Legends",        aliases:[], detail:"Mobile MOBA"},
      {rank:15, answer:"Hearthstone",           aliases:[], detail:"Kartenspiel"},
    ],
  },
  {
    id:3016, type:"ranking", title:"Top 15 größte Flughäfen der Welt", description:"Nach Passagieraufkommen", category:"Ranking", timePerTurn:30,
    items:[
      {rank:1,  answer:"Atlanta",         aliases:["hartsfield-jackson"], detail:"USA"},
      {rank:2,  answer:"Dubai",           aliases:[], detail:"VAE"},
      {rank:3,  answer:"Dallas Fort Worth",aliases:["dallas"], detail:"USA"},
      {rank:4,  answer:"London Heathrow", aliases:["heathrow"], detail:"Großbritannien"},
      {rank:5,  answer:"Tokio Haneda",    aliases:["haneda"], detail:"Japan"},
      {rank:6,  answer:"Denver",          aliases:[], detail:"USA"},
      {rank:7,  answer:"Istanbul",        aliases:[], detail:"Türkei"},
      {rank:8,  answer:"Los Angeles",     aliases:["lax"], detail:"USA"},
      {rank:9,  answer:"Chicago O'Hare",  aliases:["ohare"], detail:"USA"},
      {rank:10, answer:"Indira Gandhi (Delhi)",aliases:["delhi airport"], detail:"Indien"},
      {rank:11, answer:"Paris Charles de Gaulle",aliases:["charles de gaulle","cdg"], detail:"Frankreich"},
      {rank:12, answer:"Amsterdam Schiphol",aliases:["schiphol"], detail:"Niederlande"},
      {rank:13, answer:"Guangzhou",       aliases:[], detail:"China"},
      {rank:14, answer:"Frankfurt Flughafen",aliases:["frankfurt airport"], detail:"Deutschland"},
      {rank:15, answer:"Singapur Changi", aliases:["changi"], detail:"Singapur"},
    ],
  },
  {
    id:3017, type:"ranking", title:"Top 15 meistproduzierte Automodelle aller Zeiten", description:"Nach Gesamtstückzahl", category:"Ranking", timePerTurn:30,
    items:[
      {rank:1,  answer:"Toyota Corolla",   aliases:["corolla"],  detail:"über 50 Mio."},
      {rank:2,  answer:"Ford F-Series",    aliases:["f150","f-150"], detail:"über 40 Mio."},
      {rank:3,  answer:"VW Golf",          aliases:["golf"],     detail:"über 35 Mio."},
      {rank:4,  answer:"VW Käfer",         aliases:["käfer","beetle"], detail:"über 21 Mio."},
      {rank:5,  answer:"Toyota Hilux",     aliases:["hilux"],    detail:"über 18 Mio."},
      {rank:6,  answer:"Honda Civic",      aliases:["civic"],    detail:"über 27 Mio."},
      {rank:7,  answer:"Ford Model T",     aliases:["model t"],  detail:"über 16 Mio."},
      {rank:8,  answer:"Lada Riva",        aliases:[],           detail:"über 19 Mio."},
      {rank:9,  answer:"Toyota Camry",     aliases:["camry"],    detail:"über 19 Mio."},
      {rank:10, answer:"Volkswagen Passat",aliases:["passat"],   detail:"über 30 Mio."},
      {rank:11, answer:"Chevrolet Impala", aliases:["impala"],   detail:"über 16 Mio."},
      {rank:12, answer:"Honda Accord",     aliases:["accord"],   detail:"über 19 Mio."},
      {rank:13, answer:"Ford Escort",      aliases:["escort"],   detail:"über 20 Mio."},
      {rank:14, answer:"Renault Clio",     aliases:["clio"],     detail:"über 16 Mio."},
      {rank:15, answer:"Fiat 124",         aliases:[],           detail:"über 15 Mio."},
    ],
  },
  {
    id:3018, type:"ranking", title:"Top 15 meistgestreamte Podcasts weltweit", description:"Nach Hörerzahl", category:"Ranking", timePerTurn:30,
    items:[
      {rank:1,  answer:"The Joe Rogan Experience",aliases:["joe rogan"], detail:"USA"},
      {rank:2,  answer:"Call Her Daddy",   aliases:[], detail:"USA"},
      {rank:3,  answer:"Crime Junkie",     aliases:[], detail:"True Crime"},
      {rank:4,  answer:"This American Life",aliases:[], detail:"USA"},
      {rank:5,  answer:"Stuff You Should Know",aliases:[], detail:"USA"},
      {rank:6,  answer:"Serial",           aliases:[], detail:"True Crime"},
      {rank:7,  answer:"The Daily",        aliases:[], detail:"New York Times"},
      {rank:8,  answer:"Fest & Flauschig", aliases:[], detail:"Deutschland"},
      {rank:9,  answer:"Gemischtes Hack",  aliases:[], detail:"Deutschland"},
      {rank:10, answer:"Baby got Business",aliases:[], detail:"Deutschland"},
      {rank:11, answer:"SmartLess",        aliases:[], detail:"USA"},
      {rank:12, answer:"My Favorite Murder",aliases:[], detail:"True Crime"},
      {rank:13, answer:"Armchair Expert",  aliases:[], detail:"USA"},
      {rank:14, answer:"Lex Fridman Podcast",aliases:["lex fridman"], detail:"Tech/KI"},
      {rank:15, answer:"Verbrechen von nebenan",aliases:[], detail:"Deutschland"},
    ],
  },
  {
    id:3019, type:"ranking", title:"Top 10 schnellste Tiere in der Luft", description:"Nach Höchstgeschwindigkeit", category:"Ranking", timePerTurn:30,
    items:[
      {rank:1,  answer:"Wanderfalke",     aliases:["peregrine falcon"], detail:"390 km/h im Sturzflug"},
      {rank:2,  answer:"Weißkopf-Seeadler",aliases:["bald eagle"],      detail:"160 km/h"},
      {rank:3,  answer:"Stachelschwanzsegler",aliases:["needletail"],   detail:"170 km/h"},
      {rank:4,  answer:"Gerfalke",         aliases:["gyrfalcon"],        detail:"130 km/h"},
      {rank:5,  answer:"Spießflughuhn",    aliases:["spine-tailed swift"],detail:"110 km/h"},
      {rank:6,  answer:"Eurasischer Mauersegler",aliases:["common swift"],detail:"110 km/h"},
      {rank:7,  answer:"Fregattvogel",     aliases:["frigatebird"],      detail:"95 km/h"},
      {rank:8,  answer:"Kanadagans",       aliases:["canada goose"],     detail:"90 km/h"},
      {rank:9,  answer:"Stockente",        aliases:["mallard"],          detail:"105 km/h"},
      {rank:10, answer:"Kolibri",          aliases:["hummingbird"],      detail:"60 km/h (relativ am schnellsten)"},
    ],
  },
  {
    id:3020, type:"ranking", title:"Top 15 meistverkaufte Bücher des 21. Jahrhunderts", description:"Geschätzte Verkäufe seit 2000", category:"Ranking", timePerTurn:35,
    items:[
      {rank:1,  answer:"Harry Potter und der Halbblutprinz",aliases:["harry potter 6","half-blood prince"], detail:"65 Mio."},
      {rank:2,  answer:"Der Hobbit (Filmausgabe)", aliases:["hobbit film edition"], detail:"Re-Release"},
      {rank:3,  answer:"Fifty Shades of Grey",     aliases:["50 shades"], detail:"150 Mio."},
      {rank:4,  answer:"Die Tribute von Panem",     aliases:["hunger games"], detail:"100 Mio."},
      {rank:5,  answer:"Twilight – Bis(s) zum Morgengrauen",aliases:["twilight"], detail:"120 Mio."},
      {rank:6,  answer:"Der Da Vinci Code",         aliases:["da vinci code","sakrileg"], detail:"80 Mio."},
      {rank:7,  answer:"Eat Pray Love",             aliases:[], detail:"Memoiren"},
      {rank:8,  answer:"Der Alchimist",              aliases:["alchemist"], detail:"Coelho"},
      {rank:9,  answer:"Gone Girl",                  aliases:["das perfekte opfer"], detail:"Thriller"},
      {rank:10, answer:"Verblendung",                aliases:["girl with the dragon tattoo","millennium"], detail:"Stieg Larsson"},
      {rank:11, answer:"A Game of Thrones",          aliases:["game of thrones buch"], detail:"Martin"},
      {rank:12, answer:"Der Vorleser",                aliases:["the reader"], detail:"Schlink"},
      {rank:13, answer:"Wo die Wilden Kerle wohnen",  aliases:["where the wild things are"], detail:"Kinderbuch"},
      {rank:14, answer:"Sakrileg",                    aliases:[], detail:"siehe Da Vinci Code"},
      {rank:15, answer:"Der Kurzfristige Vorteil",    aliases:["who moved my cheese"], detail:"Ratgeber"},
    ],
  },
  {
    id:3021, type:"ranking", title:"Top 15 erfolgreichste Boybands/Girlgroups", description:"Nach verkauften Alben", category:"Ranking", timePerTurn:30,
    items:[
      {rank:1,  answer:"BTS",              aliases:["bangtan boys"], detail:"K-Pop, über 35 Mio."},
      {rank:2,  answer:"Backstreet Boys",  aliases:[], detail:"über 130 Mio."},
      {rank:3,  answer:"Spice Girls",      aliases:[], detail:"über 100 Mio."},
      {rank:4,  answer:"Westlife",         aliases:[], detail:"über 55 Mio."},
      {rank:5,  answer:"NSYNC",            aliases:["n sync"], detail:"über 70 Mio."},
      {rank:6,  answer:"One Direction",    aliases:["1d"], detail:"über 70 Mio."},
      {rank:7,  answer:"Take That",        aliases:[], detail:"über 45 Mio."},
      {rank:8,  answer:"Boyzone",          aliases:[], detail:"über 25 Mio."},
      {rank:9,  answer:"Destiny's Child",  aliases:[], detail:"über 60 Mio."},
      {rank:10, answer:"Blackpink",        aliases:[], detail:"K-Pop"},
      {rank:11, answer:"New Kids on the Block",aliases:["nkotb"], detail:"über 80 Mio."},
      {rank:12, answer:"TLC",              aliases:[], detail:"über 65 Mio."},
      {rank:13, answer:"EXO",              aliases:[], detail:"K-Pop"},
      {rank:14, answer:"Jonas Brothers",   aliases:[], detail:"über 17 Mio."},
      {rank:15, answer:"Bee Gees",         aliases:[], detail:"über 220 Mio. (Band)"},
    ],
  },
  {
    id:3022, type:"ranking", title:"Top 10 größte Inseln der Welt", description:"Nach Fläche", category:"Ranking", timePerTurn:30,
    items:[
      {rank:1,  answer:"Grönland",     aliases:["greenland"],  detail:"2,16 Mio. km²"},
      {rank:2,  answer:"Neuguinea",    aliases:["new guinea"], detail:"785.000 km²"},
      {rank:3,  answer:"Borneo",       aliases:[],             detail:"748.000 km²"},
      {rank:4,  answer:"Madagaskar",   aliases:["madagascar"], detail:"587.000 km²"},
      {rank:5,  answer:"Baffininsel",  aliases:["baffin island"],detail:"507.000 km²"},
      {rank:6,  answer:"Sumatra",      aliases:[],             detail:"473.000 km²"},
      {rank:7,  answer:"Honshu",       aliases:[],             detail:"227.000 km² – Japan"},
      {rank:8,  answer:"Großbritannien",aliases:["great britain"],detail:"209.000 km²"},
      {rank:9,  answer:"Victoria-Insel",aliases:["victoria island"],detail:"217.000 km² – Kanada"},
      {rank:10, answer:"Ellesmere-Insel",aliases:["ellesmere island"],detail:"196.000 km² – Kanada"},
    ],
  },
  {
    id:3023, type:"ranking", title:"Top 15 meistgewonnene Grammy-Künstler", description:"Nach Anzahl gewonnener Grammys", category:"Ranking", timePerTurn:30,
    items:[
      {rank:1,  answer:"Beyoncé",         aliases:["beyonce"], detail:"32 Grammys"},
      {rank:2,  answer:"Quincy Jones",    aliases:[], detail:"28 Grammys"},
      {rank:3,  answer:"Georg Solti",     aliases:["georg solti"], detail:"31 Grammys"},
      {rank:4,  answer:"Alison Krauss",   aliases:[], detail:"27 Grammys"},
      {rank:5,  answer:"Chick Corea",     aliases:[], detail:"23 Grammys"},
      {rank:6,  answer:"Stevie Wonder",   aliases:[], detail:"25 Grammys"},
      {rank:7,  answer:"Kanye West",      aliases:["ye"], detail:"24 Grammys"},
      {rank:8,  answer:"Jay-Z",           aliases:["jay z"], detail:"24 Grammys"},
      {rank:9,  answer:"Vince Gill",      aliases:[], detail:"22 Grammys"},
      {rank:10, answer:"Kendrick Lamar",  aliases:[], detail:"22 Grammys"},
      {rank:11, answer:"John Williams",   aliases:[], detail:"26 Grammys"},
      {rank:12, answer:"Pierre Boulez",   aliases:[], detail:"26 Grammys"},
      {rank:13, answer:"U2",              aliases:[], detail:"22 Grammys"},
      {rank:14, answer:"Adele",           aliases:[], detail:"16 Grammys"},
      {rank:15, answer:"Taylor Swift",    aliases:[], detail:"14 Grammys"},
    ],
  },
  {
    id:3024, type:"ranking", title:"Top 15 berühmteste Statuen und Denkmäler der Welt", description:"Nach weltweiter Bekanntheit", category:"Ranking", timePerTurn:30,
    items:[
      {rank:1,  answer:"Freiheitsstatue",     aliases:["statue of liberty"], detail:"New York"},
      {rank:2,  answer:"Christus der Erlöser",aliases:["christ the redeemer"], detail:"Rio de Janeiro"},
      {rank:3,  answer:"Eiffelturm",          aliases:[], detail:"Paris (Bauwerk)"},
      {rank:4,  answer:"David",               aliases:["david von michelangelo"], detail:"Florenz"},
      {rank:5,  answer:"Sphinx von Gizeh",    aliases:["sphinx"], detail:"Ägypten"},
      {rank:6,  answer:"Mount Rushmore",      aliases:[], detail:"USA"},
      {rank:7,  answer:"Der kleine Merman",   aliases:["little mermaid"], detail:"Kopenhagen"},
      {rank:8,  answer:"Motherland Calls",    aliases:["mutter heimat"], detail:"Russland"},
      {rank:9,  answer:"Big Buddha (Hongkong)",aliases:["tian tan buddha"], detail:"Hongkong"},
      {rank:10, answer:"Manneken Pis",        aliases:[], detail:"Brüssel"},
      {rank:11, answer:"Spring Temple Buddha",aliases:[], detail:"China – höchste Statue"},
      {rank:12, answer:"Stone of Destiny",    aliases:[], detail:"Schottland"},
      {rank:13, answer:"Easter Island Statues",aliases:["moai","osterinsel statuen"], detail:"Chile"},
      {rank:14, answer:"Brandenburger Tor",   aliases:[], detail:"Berlin"},
      {rank:15, answer:"Atomium",             aliases:[], detail:"Brüssel"},
    ],
  },
  {
    id:3025, type:"ranking", title:"Top 15 teuerste Spirituosen-Marken der Welt", description:"Nach Markenwert/Prestige", category:"Ranking", timePerTurn:30,
    items:[
      {rank:1,  answer:"Hennessy",        aliases:[], detail:"Cognac"},
      {rank:2,  answer:"Johnnie Walker",  aliases:[], detail:"Whisky"},
      {rank:3,  answer:"Jack Daniel's",   aliases:["jack daniels"], detail:"Whiskey"},
      {rank:4,  answer:"Macallan",        aliases:["the macallan"], detail:"Single Malt"},
      {rank:5,  answer:"Don Julio",       aliases:[], detail:"Tequila"},
      {rank:6,  answer:"Grey Goose",      aliases:[], detail:"Vodka"},
      {rank:7,  answer:"Moët & Chandon",  aliases:["moet chandon"], detail:"Champagner"},
      {rank:8,  answer:"Dom Pérignon",    aliases:["dom perignon"], detail:"Champagner"},
      {rank:9,  answer:"Absolut Vodka",   aliases:["absolut"], detail:"Vodka"},
      {rank:10, answer:"Bacardi",         aliases:[], detail:"Rum"},
      {rank:11, answer:"Patrón",          aliases:["patron"], detail:"Tequila"},
      {rank:12, answer:"Glenfiddich",     aliases:[], detail:"Single Malt"},
      {rank:13, answer:"Jameson",         aliases:[], detail:"Irish Whiskey"},
      {rank:14, answer:"Bombay Sapphire", aliases:[], detail:"Gin"},
      {rank:15, answer:"Veuve Clicquot",  aliases:[], detail:"Champagner"},
    ],
  },
  {
    id:3026, type:"ranking", title:"Top 15 berühmteste Wissenschaftler der Geschichte", description:"Nach Einfluss auf die Wissenschaft", category:"Ranking", timePerTurn:30,
    items:[
      {rank:1,  answer:"Albert Einstein",   aliases:["einstein"], detail:"Relativitätstheorie"},
      {rank:2,  answer:"Isaac Newton",      aliases:["newton"], detail:"Gravitationsgesetz"},
      {rank:3,  answer:"Charles Darwin",    aliases:["darwin"], detail:"Evolutionstheorie"},
      {rank:4,  answer:"Marie Curie",       aliases:["curie"], detail:"Radioaktivität"},
      {rank:5,  answer:"Galileo Galilei",   aliases:["galileo"], detail:"Astronomie"},
      {rank:6,  answer:"Nikola Tesla",      aliases:["tesla"], detail:"Elektrotechnik"},
      {rank:7,  answer:"Stephen Hawking",   aliases:["hawking"], detail:"Schwarze Löcher"},
      {rank:8,  answer:"Leonardo da Vinci", aliases:["da vinci"], detail:"Universalgelehrter"},
      {rank:9,  answer:"Louis Pasteur",     aliases:["pasteur"], detail:"Mikrobiologie"},
      {rank:10, answer:"Niels Bohr",        aliases:["bohr"], detail:"Atommodell"},
      {rank:11, answer:"Alan Turing",       aliases:["turing"], detail:"Informatik"},
      {rank:12, answer:"Gregor Mendel",     aliases:["mendel"], detail:"Genetik"},
      {rank:13, answer:"Werner Heisenberg", aliases:["heisenberg"], detail:"Quantenmechanik"},
      {rank:14, answer:"Alexander Fleming", aliases:["fleming"], detail:"Penicillin"},
      {rank:15, answer:"Rosalind Franklin", aliases:["franklin"], detail:"DNA-Struktur"},
    ],
  },
  {
    id:3027, type:"ranking", title:"Top 15 erfolgreichste Animationsfilme aller Zeiten", description:"Nach weltweiten Einnahmen", category:"Ranking", timePerTurn:30,
    items:[
      {rank:1,  answer:"Inside Out 2",         aliases:["alles steht kopf 2"], detail:"über 1,6 Mrd. $"},
      {rank:2,  answer:"Der König der Löwen (2019)",aliases:["lion king 2019"], detail:"1,66 Mrd. $"},
      {rank:3,  answer:"Frozen II",            aliases:["die eiskönigin 2"], detail:"1,45 Mrd. $"},
      {rank:4,  answer:"Der Super Mario Bros. Film",aliases:["super mario film"], detail:"1,36 Mrd. $"},
      {rank:5,  answer:"Minions",              aliases:[], detail:"1,16 Mrd. $"},
      {rank:6,  answer:"Frozen",               aliases:["die eiskönigin"], detail:"1,28 Mrd. $"},
      {rank:7,  answer:"Toy Story 4",          aliases:[], detail:"1,07 Mrd. $"},
      {rank:8,  answer:"Findet Dorie",         aliases:["finding dory"], detail:"1,03 Mrd. $"},
      {rank:9,  answer:"Ich – Einfach unverbesserlich 3",aliases:["despicable me 3"], detail:"1,03 Mrd. $"},
      {rank:10, answer:"Zoomania",             aliases:["zootopia"], detail:"1,02 Mrd. $"},
      {rank:11, answer:"Toy Story 3",          aliases:[], detail:"1,07 Mrd. $"},
      {rank:12, answer:"Die Unglaublichen 2",  aliases:["incredibles 2"], detail:"1,24 Mrd. $"},
      {rank:13, answer:"Shrek 2",              aliases:[], detail:"930 Mio. $"},
      {rank:14, answer:"Despicable Me 2",      aliases:["ich einfach unverbesserlich 2"], detail:"970 Mio. $"},
      {rank:15, answer:"Moana 2",              aliases:["vaiana 2"], detail:"über 1 Mrd. $"},
    ],
  },
  {
    id:3028, type:"ranking", title:"Top 10 meistproduzierten Rohstoffe der Welt", description:"Nach jährlicher Fördermenge", category:"Ranking", timePerTurn:30,
    items:[
      {rank:1,  answer:"Kohle",      aliases:[],            detail:"über 8 Mrd. Tonnen/Jahr"},
      {rank:2,  answer:"Erdöl",      aliases:["öl","oil"],   detail:"über 4 Mrd. Tonnen/Jahr"},
      {rank:3,  answer:"Eisenerz",   aliases:["eisen"],      detail:"über 2,5 Mrd. Tonnen/Jahr"},
      {rank:4,  answer:"Erdgas",     aliases:["gas"],        detail:"über 4 Billionen m³"},
      {rank:5,  answer:"Bauxit",     aliases:[],             detail:"über 380 Mio. Tonnen"},
      {rank:6,  answer:"Kupfer",     aliases:[],             detail:"über 20 Mio. Tonnen"},
      {rank:7,  answer:"Phosphat",   aliases:[],             detail:"über 220 Mio. Tonnen"},
      {rank:8,  answer:"Salz",       aliases:[],             detail:"über 290 Mio. Tonnen"},
      {rank:9,  answer:"Zink",       aliases:[],             detail:"über 12 Mio. Tonnen"},
      {rank:10, answer:"Gold",       aliases:[],             detail:"über 3.000 Tonnen"},
    ],
  },
  {
    id:3029, type:"ranking", title:"Top 15 meistgesprochene Sprachen nach Muttersprachlern", description:"Nur Muttersprachler, nicht Zweitsprache", category:"Ranking", timePerTurn:30,
    items:[
      {rank:1,  answer:"Mandarin",     aliases:["chinesisch"], detail:"~940 Mio."},
      {rank:2,  answer:"Spanisch",     aliases:["spanish"],    detail:"~485 Mio."},
      {rank:3,  answer:"Englisch",     aliases:["english"],    detail:"~380 Mio."},
      {rank:4,  answer:"Hindi",        aliases:[],             detail:"~345 Mio."},
      {rank:5,  answer:"Portugiesisch",aliases:["portuguese"], detail:"~235 Mio."},
      {rank:6,  answer:"Bengalisch",   aliases:["bengali"],    detail:"~230 Mio."},
      {rank:7,  answer:"Russisch",     aliases:["russian"],    detail:"~150 Mio."},
      {rank:8,  answer:"Japanisch",    aliases:["japanese"],   detail:"~125 Mio."},
      {rank:9,  answer:"Vietnamesisch",aliases:["vietnamese"], detail:"~85 Mio."},
      {rank:10, answer:"Türkisch",     aliases:["turkish"],    detail:"~80 Mio."},
      {rank:11, answer:"Koreanisch",   aliases:["korean"],     detail:"~80 Mio."},
      {rank:12, answer:"Französisch",  aliases:["french"],     detail:"~80 Mio."},
      {rank:13, answer:"Deutsch",      aliases:["german"],     detail:"~75 Mio."},
      {rank:14, answer:"Urdu",         aliases:[],             detail:"~70 Mio."},
      {rank:15, answer:"Italienisch",  aliases:["italian"],    detail:"~65 Mio."},
    ],
  },
  {
    id:3030, type:"ranking", title:"Top 15 meistdekorierte Olympioniken aller Zeiten", description:"Nach Anzahl Olympia-Medaillen (gesamt)", category:"Ranking", timePerTurn:30,
    items:[
      {rank:1,  answer:"Michael Phelps",   aliases:["phelps"], detail:"28 Medaillen – Schwimmen"},
      {rank:2,  answer:"Larisa Latynina",  aliases:["latynina"], detail:"18 Medaillen – Turnen"},
      {rank:3,  answer:"Nikolai Andrianow",aliases:["andrianov"], detail:"15 Medaillen – Turnen"},
      {rank:4,  answer:"Marit Bjørgen",    aliases:["bjorgen"], detail:"15 Medaillen – Ski"},
      {rank:5,  answer:"Ole Einar Bjørndalen",aliases:["bjorndalen"], detail:"13 Medaillen – Biathlon"},
      {rank:6,  answer:"Boris Schachlin",  aliases:["shakhlin"], detail:"13 Medaillen – Turnen"},
      {rank:7,  answer:"Edoardo Mangiarotti",aliases:["mangiarotti"], detail:"13 Medaillen – Fechten"},
      {rank:8,  answer:"Takashi Ono",      aliases:[], detail:"13 Medaillen – Turnen"},
      {rank:9,  answer:"Paavo Nurmi",      aliases:["nurmi"], detail:"12 Medaillen – Leichtathletik"},
      {rank:10, answer:"Birgit Fischer",   aliases:["fischer"], detail:"12 Medaillen – Kanu"},
      {rank:11, answer:"Sawao Kato",       aliases:["kato"], detail:"12 Medaillen – Turnen"},
      {rank:12, answer:"Jenny Thompson",   aliases:["thompson"], detail:"12 Medaillen – Schwimmen"},
      {rank:13, answer:"Dara Torres",      aliases:["torres"], detail:"12 Medaillen – Schwimmen"},
      {rank:14, answer:"Allyson Felix",    aliases:["felix"], detail:"11 Medaillen – Leichtathletik"},
      {rank:15, answer:"Usain Bolt",       aliases:["bolt"], detail:"8 Medaillen – Sprint"},
    ],
  },
];
